### PR TITLE
fix: fix migrator bug

### LINKED ISSUE #3108: [Bug][Module Name] commit_file migration script is not idempotent
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

`20220913_commitfile_add_length.go` depends on  gitlab api `dal` instance.
the script would fail if gitlab plugin is missing.
however, the script won't work anymore even if I bring gitlab plugin back
image

### What you expected to happen

migration script should be working when gitlab became available.

### How to reproduce

1. make sure the script is in pending status
2. fire up devlake with `PLUGIN=github make dev`
3. call /procced-db-migraion, fail
4. restart devlake with `make dev`
5. call /process-db-migration
6. see error

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #3126: [Bug][jenkins] migrationscripts JenkinsBuildRepo0916 use double & for batch save
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

image
image

### What you expected to happen

migrationscripts  sucess

### How to reproduce

see the code
or try to run the  migrationscripts JenkinsBuildRepo0916 with no empty data on table build.

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #3131: [Bug][migrator] migrator failed lost error info about witch failed.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

image

as the picture showing
when the migrator failed
we can not get the failed message about witch migration script faild.

### What you expected to happen

Add the script data when it have some error.

### How to reproduce

see the error message with an fail migration script.

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mappjzc**
# Summary
Add Re Executability to addCommitFilePathLength.
Fix a type error on modifyJenkinsBuild.
Add error message on migrator execute.

### Does this close any open issues?
Closes #3108 
Closes #3126 
Closes #3131 

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: models/migrationscripts/20220913_commitfile_add_length.go [hunk 1]
```diff
@@ -68,11 +68,28 @@ func (CommitFileComponentBak) TableName() string {
...
 
 func (*addCommitFilePathLength) Up(ctx context.Context, db *gorm.DB) errors.Error {
-	err := db.Migrator().RenameTable(&CommitFile{}, &CommitFileAddLengthBak{})
-	if err != nil {
-		return errors.Default.Wrap(err, "error no rename commit_file to commit_files_bak")
+	var err error
+
+	// commit_files
+	// rename the commit_file_bak to cache old table
+	if db.Migrator().HasTable(&CommitFileAddLengthBak{}) {
```
Comment (klesh) [inline models/migrationscripts/20220913_commitfile_add_length.go:75]: What if the user wants to go back to the old version when upgrade failed?
I suggest we use a `defer` function, revert to the original state if there was any err, or delete the backup table otherwise

File: models/migrationscripts/20220913_commitfile_add_length.go [hunk 2]
```diff
@@ -67,13 +68,39 @@ func (CommitFileComponentBak) TableName() string {
 
 type addCommitFilePathLength struct{}
 
-func (*addCommitFilePathLength) Up(ctx context.Context, db *gorm.DB) errors.Error {
-	err := db.Migrator().RenameTable(&CommitFile{}, &CommitFileAddLengthBak{})
+func (*addCommitFilePathLength) Up(ctx context.Context, db *gorm.DB) (errs errors.Error) {
+	var err error
+
+	// rename the commit_file_bak to cache old table
+	err = db.Migrator().RenameTable(&CommitFile{}, &CommitFileAddLengthBak{})
```
Comment (klesh) [inline models/migrationscripts/20220913_commitfile_add_length.go:75]: shouldn't we return here if the error is not nil?

File: models/migrationscripts/20220913_commitfile_add_length.go [hunk 3]
```diff
@@ -67,13 +68,39 @@ func (CommitFileComponentBak) TableName() string {
...
+			}
+		}
+	}()
+
 	if err != nil {
 		return errors.Default.Wrap(err, "error no rename commit_file to commit_files_bak")
 	}
 
+	// create new commit_files table
 	err = db.Migrator().AutoMigrate(&CommitFileAddLength{})
```
Comment (klesh) [inline models/migrationscripts/20220913_commitfile_add_length.go:92]: same as above

File: models/migrationscripts/20220913_commitfile_add_length.go [hunk 4]
```diff
@@ -108,16 +136,40 @@ func (*addCommitFilePathLength) Up(ctx context.Context, db *gorm.DB) errors.Erro
 
 		err = batch.Add(&cf)
 		if err != nil {
-			return errors.Default.Wrap(err, "error on batch add")
+			return errors.Default.Wrap(err, "error on commit_files batch add")
 		}
 	}
 
+	// rename the commit_file_components_bak
 	err = db.Migrator().RenameTable(&CommitFileComponent{}, &CommitFileComponentBak{})
```
Comment (klesh) [inline models/migrationscripts/20220913_commitfile_add_length.go:144]: same as above

File: models/migrationscripts/20220913_commitfile_add_length.go [hunk 5]
```diff
@@ -108,16 +136,40 @@ func (*addCommitFilePathLength) Up(ctx context.Context, db *gorm.DB) errors.Erro
...
+			}
+		}
+	}()
+
 	if err != nil {
 		return errors.Default.Wrap(err, "error no rename commit_file_components to commit_file_components_bak")
 	}
 
+	// create new commit_file_components table
 	err = db.Migrator().AutoMigrate(&CommitFileComponent{})
```
Comment (klesh) [inline models/migrationscripts/20220913_commitfile_add_length.go:161]: same as above

File: models/migrationscripts/20220913_commitfile_add_length.go [hunk 6]
```diff
@@ -67,24 +68,49 @@ func (CommitFileComponentBak) TableName() string {
 
 type addCommitFilePathLength struct{}
 
-func (*addCommitFilePathLength) Up(ctx context.Context, db *gorm.DB) errors.Error {
-	err := db.Migrator().RenameTable(&CommitFile{}, &CommitFileAddLengthBak{})
+func (*addCommitFilePathLength) Up(ctx context.Context, db *gorm.DB) (errs errors.Error) {
+	var err error
+
+	// rename the commit_file_bak to cache old table
+	err = db.Migrator().RenameTable(&CommitFile{}, &CommitFileAddLengthBak{})
```
Comment (likyh) [inline models/migrationscripts/20220913_commitfile_add_length.go:75]: `CommitFile` not defined in this file. is it `CommitFileAddLength`?

**Review by likyh — APPROVED** [review]
I can find https://github.com/apache/incubator-devlake/issues/3126
and https://github.com/apache/incubator-devlake/issues/3131 .  #3108 is caused by `api.BasicRes` and it not fix. Maybe don't close it?

Others LGTM.
