### PR TITLE
Zentao update the data transformation logic

### LINKED ISSUE #5188: [Bug][Zentao] Update the data transformation logic
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Data collected from Zentao is not transformed correctly according to the DevLake data schema.

### table.issues (for issues from Zentao)
- [ ] `url`: use the Zentao issue URL, now it's empty
- [ ] `original_type`: use '{type}.{subtype}', as Zentao issues have subtypes, such as features, API, etc.
- [ ] `original_status`: for a Zentao story, use story's `{status}-{stage}` as the value
- [ ] Add the configuration for issue status mapping
- [ ] `priority`: make sure it's a meaningful name, not a number
- [ ] `module`: make sure it's a meaningful name, not a number
- [ ] `original_project`: use the project/product name
- [ ] `icon_url`: use the URL if it exists

### table.sprints

- [ ] `completed_date`: use `PlanEnd` as the value, now it uses `ClosedDate`
- [ ] `original_board_id`: use the Zentao project's id, now it uses `execution_id`

### table.boards

- [ ] `url`: use the URL of the Zentao project or product, now it's empty

### How to reproduce

Install DevLake v0.17 and collect the Zentao data.

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #5303: [Feature][Zentao] Provide configuration for type and status transformation
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a product manager, I want to measure Zentao's issue status change history by issue type. Thus, I want to transform:

- Zentao issues' `original_type` => Standard issue types, i.e. issues.`type`. For example, a standard type can be 'REQUIREMENT', 'BUG', 'INCIDENT', etc. The default conversion logic is:
   - Zentao story => `REQUIREMENT`
   - Zentao task => `TASK`
   - Zentao bug => `BUG`
- Zentao issues' `original_status` => Standard issue statuses, i.e. issues.`status`. Zentao issue status transformation should be based on issue type. For example, 

```
{
    type_1:{
       original_status_1:standard_status_1;
       original_status_2:standard_status_2;
       original_status_3:standard_status_3;
       },
    type_2:{
       original_status_1:standard_status_1;
       original_status_2:standard_status_2;
       original_status_3:standard_status_3;
       }
}
```

### Description

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mappjzc**
### Summary
Update the data transformation logic
on
table.issues 
table.sprints
table.boards

Add changelog convert
Fix and add some e2e for changes.

Add scope config zentao

### Does this close any open issues?
Closes #5188 
Closes #5303

### CODE REVIEW

File: backend/plugins/zentao/models/migrationscripts/20221121_add_init_tables.go [hunk 1]
```diff
@@ -57,11 +58,12 @@ func (*addInitTables) Up(basicRes context.BasicRes) errors.Error {
 		&archived.ZentaoTask{},
 		&archived.ZentaoAccount{},
 		&archived.ZentaoDepartment{},
+		&archived.ZentaoScopeConfig{},
 	)
 }
 
 func (*addInitTables) Version() uint64 {
-	return 20230505000001
+	return 20230530000001
```
Comment (klesh) [inline backend/plugins/zentao/models/migrationscripts/20221121_add_init_tables.go:66]: We should create a new migration script for adding new tables.
adding a new tables to an existing script is not a good practice

**Review by klesh — APPROVED** [review]
LGTM

**Review by klesh — DISMISSED** [review]
LGTM
