### PR TITLE
fix: ignore http status code 404

### LINKED ISSUE #2226: [Bug] [jira] Task failed with error 404
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

It report an error "Issue does not exist or you do not have permission to see it" when I am running jira plugin. And I'm confirmed that I have permission to all jira issues.

### What you expected to happen

It shouldn't report error.

### How to reproduce

Not sure.

## Snapshots
origin_img_v2_08aaa3bf-6483-4f18-8acd-bb07539fa26g

## Logs
5dgvVlALFi

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mindlesscloud**
# Summary

fix #2226 
Adding an function type attribute `AfterResponse` to `helper.ApiCollectorArgs`. This function would check all the HTTP responses, if the status code is 404, it returns a predefined error `helper.ErrIgnoreAndContinue`. The rest part of the `collector` will ignore this error and skip to the next HTTP request.

### Does this close any open issues?
close #2226

### CODE REVIEW

**Review by klesh — DISMISSED** [review]
LGTM

File: plugins/helper/api_client.go [hunk 1]
```diff
@@ -47,7 +47,7 @@ type ApiClient struct {
 	endpoint      string
 	headers       map[string]string
 	beforeRequest ApiClientBeforeRequest
```
Comment (likyh) [inline plugins/helper/api_client.go:49]: Maybe we can move ApiClientBeforeRequest to common as ApiClientAfterResponse to keep code consistent.

**Review by likyh — CHANGES_REQUESTED** [review]

**Review by likyh — APPROVED** [review]
LGTM
