### PR TITLE
fix(config-ui): adjust the api field

### LINKED ISSUE #4403: [Bug][Jira] The behaviour of createdDateAfter option does not fit the user scenario
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

In our situation, we do need the limited history sync feature introduced by 0.15.  
With solution implemented in 0.15, we lost issues which is created before but updated after `CreatedDateAfter` time.  
Those issues (created before but updated after) are useful when analysing, because the updating operation means it is picked up again recently.

### What do you expect to happen

We need all data which has updation after the time we specified.

### How to reproduce

No

### Anything else

_No response_

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mintsweet**
### Summary
Adjust the api field.

### Does this close any open issues?
Closes #4403

### CODE REVIEW

File: config-ui/src/pages/blueprint/components/sync-policy/index.tsx [hunk 1]
```diff
@@ -72,7 +72,7 @@ export const SyncPolicy = ({
         <div className="block">
           <h3>Time Filter *</h3>
           <p>Select the data range you wish to collect. DevLake will collect the last six months of data by default.</p>
-          <StartFromSelector value={createdDateAfter} onChange={onChangeCreatedDateAfter} />
+          <StartFromSelector value={timeAfter} onChange={onChangeCreatedDateAfter} />
```
Comment (likyh) [inline config-ui/src/pages/blueprint/components/sync-policy/index.tsx:75]: should `setCreatedDateAfter` be changed?

Comment (mintsweet) [reply config-ui/src/pages/blueprint/components/sync-policy/index.tsx]: ok, you're right.

**Review by likyh — APPROVED** [review]
