### PR TITLE
[Bitbucket] Pagination params and merged date on PRs

### LINKED ISSUE #4285: [Bug][Bitbucket] Error when running `collectApiPullRequestCommits`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I run `collectApiPullRequestCommits` with Bitbucket plugin the API that throws an error (Bad Request) when start to fetching the PR API.
image
image

### What do you expect to happen

Fetching on Bitbucket need to run without throwing an error.

### How to reproduce

Configure a Bitbucket connection and run a pipeline with any repo.

### Anything else

I think it's a problem with params that Bitbucket API expect to do pagination. 

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jrflga**
### Summary
What does this PR do?
- Fix the pagination params on Bitbucket API and add a feature to get the PR merge datetime (in order to fix the Lead Time feature on DORA for Bitbucket plugin).

### Does this close any open issues?
Closes #4285

### Screenshots
After these modifications, DORA metrics dashboard shows these metrics.
Imagem 01-02-2023 às 16 57

### CODE REVIEW

File: backend/plugins/bitbucket/tasks/pr_convertor.go [hunk 1]
```diff
@@ -70,6 +70,17 @@ func ConvertPullRequests(taskCtx plugin.SubTaskContext) errors.Error {
 		},
 		Convert: func(inputRow interface{}) ([]interface{}, errors.Error) {
 			pr := inputRow.(*models.BitbucketPullRequest)
+
+			// Getting the merge reference commit
+			mergeCommit := &models.BitbucketCommit{}
+			err = db.First(mergeCommit, dal.Where("LEFT(sha, 12) = ?", pr.MergeCommitSha))
```
Comment (likyh) [inline backend/plugins/bitbucket/tasks/pr_convertor.go:76]: I'm not sure if the function `LEFT` can be used in both MySQL and pg. Would like confirm it?

File: backend/plugins/bitbucket/tasks/api_common.go [hunk 2]
```diff
@@ -65,8 +65,8 @@ func CreateRawDataSubTaskArgs(taskCtx plugin.SubTaskContext, Table string) (*api
 func GetQuery(reqData *api.RequestData) (url.Values, errors.Error) {
 	query := url.Values{}
 	query.Set("state", "all")
-	query.Set("page", fmt.Sprintf("%v", reqData.Pager.Page))
-	query.Set("pagelen", fmt.Sprintf("%v", reqData.Pager.Size))
+	query.Set("start", fmt.Sprintf("%v", reqData.Pager.Page*reqData.Pager.Size))
```
Comment (likyh) [inline backend/plugins/bitbucket/tasks/api_common.go:68]: `reqData.Pager.Skip` = `reqData.Pager.Page*reqData.Pager.Size`

Let's use `reqData.Pager.Skip` directly.

File: backend/plugins/bitbucket/tasks/pr_convertor.go [hunk 3]
```diff
@@ -70,6 +70,17 @@ func ConvertPullRequests(taskCtx plugin.SubTaskContext) errors.Error {
...
+			if err != nil {
+				mergeCommit.CommittedDate = *pr.MergedAt
```
Comment (likyh) [inline backend/plugins/bitbucket/tasks/pr_convertor.go:78]: Actually, `pr.MergedAt` is always empty. How about set `pr.MergedAt = &mergeCommit.CommittedDate` when `err == nil` directly?

File: backend/plugins/bitbucket/tasks/api_common.go (hunk 2 above)
Comment (likyh) [reply backend/plugins/bitbucket/tasks/api_common.go:68]: I try to user start/limit, but it just reqeust the first page. That means `start/limit` are not work. https://developer.atlassian.com/cloud/bitbucket/rest/intro/#pagination

So I think `page/pagelen` is right. We need add `GetTotalPages` for collector to avoid this issue.

Comment (likyh) [reply backend/plugins/bitbucket/tasks/api_common.go:68]: https://jira.atlassian.com/browse/BCLOUD-19593

image

It looks like we can not build a query on the client and we can only request it one page by one page.

File: backend/plugins/bitbucket/tasks/pr_convertor.go (hunk 3 above)
Comment (jrflga) [reply backend/plugins/bitbucket/tasks/pr_convertor.go:78]: That make sense. I'll change this.

File: backend/plugins/bitbucket/tasks/pr_convertor.go (hunk 1 above)
Comment (jrflga) [reply backend/plugins/bitbucket/tasks/pr_convertor.go:76]: I've tested with MySQL and a PostgreSQL instance, and it worked fine. According to the documentation, the function exists in both databases.
https://www.postgresql.org/docs/current/functions-string.html
https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_left

File: backend/plugins/bitbucket/tasks/api_common.go (hunk 2 above)
Comment (jrflga) [reply backend/plugins/bitbucket/tasks/api_common.go:68]: You're right; sorry for the change to start/limit. It's used on other collections of routes on Bitbucket API.
Maybe we can change how pagination on `reqData` is mounted because it's different depending on what API is used.
We have no access to the `next` property when building `GetQuery` function in `NewApiCollector`, so we can't fetch the next page.

Comment (likyh) [reply backend/plugins/bitbucket/tasks/api_common.go:68]: Yes, we need a new param in NewApiCollector to request API one by one. I'll add it. Please wait a few days.

Comment (likyh) [reply backend/plugins/bitbucket/tasks/api_common.go:68]: https://github.com/apache/incubator-devlake/pull/4320
Added a new pages `PageInOrder` to support this situation.

And I find the page token is the same when `pagelen` is the same. Maybe we can write a map to translate page to page token instead of using `PageInOrder`.

（no matter which pr is）
when pagelen=100 page=2: nextPage=67sER
when pagelen=100 page=2: nextPage= znuod
……

Comment (jrflga) [reply backend/plugins/bitbucket/tasks/api_common.go:68]: Thank you so much!
I'll change the `NewApiCollector` on Bitbucket to make use of this new param.

Maybe the `page` attribute is defined by some form of encoding?

Comment (likyh) [reply backend/plugins/bitbucket/tasks/api_common.go]: Hi, I submit a commit to complete `GetQuery`. Please take a look. If you think it's good, I'' merge this PR and cherry-pick to 0.15

Comment (jrflga) [reply backend/plugins/bitbucket/tasks/api_common.go]: @likyh, it's perfect! Thanks for the help.

**Review by likyh — APPROVED** [review]
