### PR TITLE
fix(tapd): resolve issues impacted incremental collection

### LINKED ISSUE #3710: [Bug][Tapd] Incremental collection works improperly
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Recently when we are trying to collect story_commits by incrementally, we found some minor issues:
1. when doing incremental collection, we misused UTC and time.Format for the field modified which is used in url, as tapd time are all in China, but we store all data as UTC time in db, so we need to transform time to CstZone
2. we used a wrong way to collect xxCommits, the old way will miss data which created after last modification of story/bug/task. For example, we already have story_commit which created on 2022-11-02, and that story was modified on 2022-11-01, then we collect both data on 2022-11-03, and we connected another commit to any story on 2022-11-04, then we tried to collect data again on 2022-11-05, we will not collect commits for the story which modified before 2022-11-02, because connect a commit to a story, the story's filed modified will not be changed.

### What do you expect to happen

none

### How to reproduce

none

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by warren830**
# Summary

1. use  since.In(CstZone).Format("2006-01-02") as param `modified` in Tapd URL  to update data 
2. I found that some idGenerator which we used to generate `domain layer Id` is spreading everywhere, so make some changes to order them
3. another minor issue(never influence our previous data report): the entity task used a wrong tag name for the field title 
4. I also found that bug/story/task are using an empty issue to generate their domain layer id, so I correct them in this pr

### Does this close any open issues?
Closes #3710 

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: plugins/tapd/models/migrationscripts/20221109_add_init_tables.go [hunk 1]
```diff
@@ -136,7 +136,7 @@ func (*addInitTables) Up(basicRes core.BasicRes) errors.Error {
 }
 
 func (*addInitTables) Version() uint64 {
-	return 20221013201138
```
Comment (abeizn) [inline plugins/tapd/models/migrationscripts/20221109_add_init_tables.go:139]: need updated version?

File: plugins/tapd/tasks/bug_commit_collector.go [hunk 2]
```diff
@@ -77,24 +52,24 @@ func CollectBugCommits(taskCtx core.SubTaskContext) errors.Error {
...
-	iterator, err := helper.NewDalCursorIterator(db, cursor, reflect.TypeOf(SimpleBug{}))
+	iterator, err := helper.NewDalCursorIterator(db, cursor, reflect.TypeOf(models.Input{}))
 
 	if err != nil {
 		return err
 	}
 	collector, err := helper.NewApiCollector(helper.ApiCollectorArgs{
 		RawDataSubTaskArgs: *rawDataSubTaskArgs,
-		Incremental:        incremental,
+		Incremental:        since == nil,
```
Comment (abeizn) [inline plugins/tapd/tasks/bug_commit_collector.go:62]: since != nil ?

File: plugins/tapd/tasks/iteration_collector.go [hunk 3]
```diff
@@ -65,6 +65,7 @@ func CollectIterations(taskCtx core.SubTaskContext) errors.Error {
 		Incremental:        incremental,
 		ApiClient:          data.ApiClient,
 		PageSize:           100,
+		Concurrency:        3,
```
Comment (abeizn) [inline plugins/tapd/tasks/iteration_collector.go:68]: why need to set Concurrency?

File: plugins/tapd/tasks/story_bug_collector.go [hunk 4]
```diff
@@ -42,52 +38,33 @@ func CollectStoryBugs(taskCtx core.SubTaskContext) errors.Error {
...
-	iterator, err := helper.NewDalCursorIterator(db, cursor, reflect.TypeOf(SimpleStory{}))
+	iterator, err := helper.NewDalCursorIterator(db, cursor, reflect.TypeOf(models.Input{}))
 	if err != nil {
 		return err
 	}
 	collector, err := helper.NewApiCollector(helper.ApiCollectorArgs{
 		RawDataSubTaskArgs: *rawDataSubTaskArgs,
 		ApiClient:          data.ApiClient,
-		Incremental:        incremental,
+		Incremental:        since == nil,
```
Comment (abeizn) [inline plugins/tapd/tasks/story_bug_collector.go:60]: same as above

File: plugins/tapd/tasks/story_commit_collector.go [hunk 5]
```diff
@@ -78,23 +52,23 @@ func CollectStoryCommits(taskCtx core.SubTaskContext) errors.Error {
...
 	}
-	iterator, err := helper.NewDalCursorIterator(db, cursor, reflect.TypeOf(SimpleStory{}))
+	iterator, err := helper.NewDalCursorIterator(db, cursor, reflect.TypeOf(models.Input{}))
 	if err != nil {
 		return err
 	}
 	collector, err := helper.NewApiCollector(helper.ApiCollectorArgs{
 		RawDataSubTaskArgs: *rawDataSubTaskArgs,
-		Incremental:        incremental,
+		Incremental:        since == nil,
```
Comment (abeizn) [inline plugins/tapd/tasks/story_commit_collector.go:61]: same

File: plugins/tapd/tasks/story_status_collector.go [hunk 6]
```diff
@@ -38,7 +38,6 @@ func CollectStoryStatus(taskCtx core.SubTaskContext) errors.Error {
 	collector, err := helper.NewApiCollector(helper.ApiCollectorArgs{
 		RawDataSubTaskArgs: *rawDataSubTaskArgs,
 		ApiClient:          data.ApiClient,
-		PageSize:           100,
```
Comment (abeizn) [inline plugins/tapd/tasks/story_status_collector.go:41]: why?

File: plugins/tapd/tasks/task_commit_collector.go [hunk 7]
```diff
@@ -78,23 +52,23 @@ func CollectTaskCommits(taskCtx core.SubTaskContext) errors.Error {
...
 	}
-	iterator, err := helper.NewDalCursorIterator(db, cursor, reflect.TypeOf(SimpleTask{}))
+	iterator, err := helper.NewDalCursorIterator(db, cursor, reflect.TypeOf(models.Input{}))
 	if err != nil {
 		return err
 	}
 	collector, err := helper.NewApiCollector(helper.ApiCollectorArgs{
 		RawDataSubTaskArgs: *rawDataSubTaskArgs,
-		Incremental:        incremental,
+		Incremental:        since == nil,
```
Comment (abeizn) [inline plugins/tapd/tasks/task_commit_collector.go:61]: same

File: helpers/migrationhelper/migrationhelper.go [hunk 8]
```diff
@@ -183,7 +183,7 @@ func TransformTable[S any, D any](
 ) (err errors.Error) {
 	db := basicRes.GetDal()
 	tmpTableName := fmt.Sprintf("%s_%s", tableName, hashScript(script))
-
+	db.Dialect()
```
Comment (abeizn) [inline helpers/migrationhelper/migrationhelper.go:186]: What is the point of adding this line?

File: plugins/tapd/models/migrationscripts/20221109_add_init_tables.go (hunk 1 above)
Comment (warren830) [reply plugins/tapd/models/migrationscripts/20221109_add_init_tables.go:139]: Yes, this will also run even this had been run before

File: plugins/tapd/tasks/iteration_collector.go (hunk 3 above)
Comment (warren830) [reply plugins/tapd/tasks/iteration_collector.go:68]: Because we dont have too many iterations, so 3 is good enough, otherwise, we will send too many requests that will get nothing

File: plugins/tapd/tasks/story_status_collector.go (hunk 6 above)
Comment (warren830) [reply plugins/tapd/tasks/story_status_collector.go:41]: Because this api does not support limit

File: helpers/migrationhelper/migrationhelper.go (hunk 8 above)
Comment (warren830) [reply helpers/migrationhelper/migrationhelper.go]: fixed

File: plugins/tapd/tasks/task_commit_collector.go (hunk 7 above)
Comment (warren830) [reply plugins/tapd/tasks/task_commit_collector.go]: fixed

File: plugins/tapd/tasks/story_commit_collector.go (hunk 5 above)
Comment (warren830) [reply plugins/tapd/tasks/story_commit_collector.go]: fixed

File: plugins/tapd/tasks/story_bug_collector.go (hunk 4 above)
Comment (warren830) [reply plugins/tapd/tasks/story_bug_collector.go]: fixed

File: plugins/tapd/tasks/bug_commit_collector.go (hunk 2 above)
Comment (warren830) [reply plugins/tapd/tasks/bug_commit_collector.go]: fixed

**Review by abeizn — COMMENTED** [review]
we don't update the package-lock.json

**Review by abeizn — APPROVED** [review]
LGTM
