### PR TITLE
fix: remove createdDateAfter completely

### LINKED ISSUE #4403: [Bug][Jira] The behaviour of createdDateAfter option does not fit the user scenario
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

In our situation, we do need the limited history sync feature introduced by 0.15.  
With solution implemented in 0.15, we lost issues which is created before but updated after `CreatedDateAfter` time.  
Those issues (created before but updated after) are useful when analysing, because the updating operation means it is picked up again recently.

### What do you expect to happen

We need all data which has updation after the time we specified.

### How to reproduce

No

### Anything else

_No response_

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by klesh**
### Summary
According to the Plan of  Attack from #4403, this is the last step of the BE side to replace `createdDateAfter` with `timeAfter`

@mintsweet  the `config-ui` may have to be modified accordingly. you may close #4403 from your PR, thanks.

### Does this close any open issues?
Part of #4403

### CODE REVIEW

**Review by likyh — APPROVED** [review]

File: backend/helpers/pluginhelper/api/api_collector_with_state.go [hunk 1]
```diff
@@ -66,37 +64,17 @@ func NewApiCollectorWithStateEx(args RawDataSubTaskArgs, createdDateAfter *time.
...
-		return false
-	}
-	// prioritize TimeAfter parameter: collector should filter data by `updated_date`
 	if m.TimeAfter != nil {
 		return m.LatestState.TimeAfter == nil || !m.TimeAfter.Before(*m.LatestState.TimeAfter)
 	}
-	// Deprecating(timeAfter): to be removed
-	// fallback to CreatedDateAfter: collector should filter data by `created_date`
-	return m.LatestState.CreatedDateAfter == nil || m.CreatedDateAfter != nil && !m.CreatedDateAfter.Before(*m.LatestState.CreatedDateAfter)
+	return m.LatestState.LatestSuccessStart != nil
```
Comment (likyh) [inline backend/helpers/pluginhelper/api/api_collector_with_state.go:77]: no

Comment (likyh) [reply backend/helpers/pluginhelper/api/api_collector_with_state.go:77]: check LatestSuccessStart first. Because when LatestState exists but the latest collection fails (LatestSuccessStart=nil), it will be true that `m.TimeAfter != nil && m.LatestState.TimeAfter == nil`.

**Review by likyh — CHANGES_REQUESTED** [review]
a logic bug

File: backend/helpers/pluginhelper/api/api_collector_with_state.go (hunk 1 above)
Comment (klesh) [reply backend/helpers/pluginhelper/api/api_collector_with_state.go]: You are correct, thanks for pointing our. fixed

**Review by likyh — APPROVED** [review]
