### PR TITLE
fix: Fix wrong package name in domain ids

### LINKED ISSUE #4970: [Bug][Azure] Table cicd_tasks have records with id like 'github%' and cicd_scope_id like 'azure%'
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

5582f847-3bd2-4be6-a426-d77ea0f20bcd

### What do you expect to happen

This kind of records should not exist.

### How to reproduce

Not sure

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by CamilleTeruel**
### Summary
Fix remotePluginImpl.RootPkgPath that caused the domain id generator to generate wrong plugin names in domain ids..

### Does this close any open issues?
Closes #4970

### CODE REVIEW

File: backend/server/services/remote/plugin/plugin_impl.go [hunk 1]
```diff
@@ -164,11 +164,12 @@ func (p *remotePluginImpl) Description() string {
 }
 
 func (p *remotePluginImpl) RootPkgPath() string {
-	// RootPkgPath is only used to find to which plugin a given type belongs.
-	// This in turn is only used by DomainIdGenerator.
-	// Remote plugins define tool layer types in another language,
-	// so the reflective implementation of NewDomainIdGenerator cannot work.
-	return ""
```
Comment (keon94) [inline backend/server/services/remote/plugin/plugin_impl.go:171]: how was this causing wrong plugin-names to end up in the domain ID?

Comment (CamilleTeruel) [reply backend/server/services/remote/plugin/plugin_impl.go:171]: DomainIdGenerator uses FindPluginNameBySubPkgPath that returns the name of the first plugin whose RootPkgPath is a prefix of the type package path. So this empty string makes FindPluginNameBySubPkgPath believe all types belong to any remote plugin.

**Review by keon94 — APPROVED** [review]

**Comment by keon94** [comment]
Lgtm
