### PR TITLE
Commit file

### LINKED ISSUE #2949: [Bug][Github Plugin] trino project syned failed for Data too long for column 'id' in table `commit_files`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

trino project from github syned failed for Data too long for column 'id' in table `commit_files` 

```
[9.920ms] [rows:0] INSERT INTO `commit_files` (`id`,`created_at`,`updated_at`,`_raw_data_params`,`_raw_data_table`,`_raw_data_id`,`_raw_data_remark`,`commit_sha`,`file_path`,`additions`,`deletions`) VALUES ('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/AzureTransactionLogSynchronizer.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/AzureTransactionLogSynchronizer.java',78,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/NoIsolationSynchronizer.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/NoIsolationSynchronizer.java',60,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3TransactionLogSynchronizer.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3TransactionLogSynchronizer.java',315,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionConflictException.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionConflictException.java',23,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogSynchronizer.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogSynchronizer.java',33,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogSynchronizerManager.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogSynchronizerManager.java',57,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogWriter.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogWriter.java',113,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogWriterFactory.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogWriterFactory.java',44,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AbstractTestDeltaLakeCreateTableStatistics.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AbstractTestDeltaLakeCreateTableStatistics.java',537,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AccessTrackingFileSystem.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AccessTrackingFileSystem.java',134,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeAwsConnectorSmokeTest.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeAwsConnectorSmokeTest.java',74,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java',1519,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java',273,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeDockerizedMinioDataLake.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeDockerizedMinioDataLake.java',42,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java',253,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/FileTestingTransactionLogSynchronizer.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/FileTestingTransactionLogSynchronizer.java',48,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java',239,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsStorage.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsStorage.java',135,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java',512,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java',147,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java',103,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorSmokeTest.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorSmokeTest.java',207,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateTableStatistics.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateTableStatistics.java',108,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateTableStatisticsOptimizedWriter.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateTableStatisticsOptimizedWriter.java',28,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDatabricksConnectorTest.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDatabricksConnectorTest.java',23,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDelete.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDelete.java',277,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java',510,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeOptimizedWriterConnectorSmokeTest.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeOptimizedWriterConnectorSmokeTest.java',41,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeOssDeltaLakeConnectorTest.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeOssDeltaLakeConnectorTest.java',23,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java',211,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePartitioning.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePartitioning.java',181,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePerTransactionMetastoreCache.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePerTransactionMetastoreCache.java',237,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePlugin.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePlugin.java',100,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePreferredPartitioning.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePreferredPartitioning.java',148,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeReadTimestamps.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeReadTimestamps.java',180,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java',308,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableStatistics.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableStatistics.java',142,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeUpdate.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeUpdate.java',194,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeWriter.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeWriter.java',205,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestPredicatePushdown.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestPredicatePushdown.java',249,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestReadJsonTransactionLog.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestReadJsonTransactionLog.java',133,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestSplitPruning.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestSplitPruning.java',422,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java',711,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingComplexTypeManager.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingComplexTypeManager.java',51,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakeExtensionsModule.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakeExtensionsModule.java',33,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakePlugin.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakePlugin.java',29,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TrackingTransactionLogAccess.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TrackingTransactionLogAccess.java',57,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreStatistics.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreStatistics.java',449,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java',289,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastoreConfig.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastoreConfig.java',46,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestDeltaLakeParquetStatisticsUtils.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestDeltaLakeParquetStatisticsUtils.java',205,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestDeltaLakeSchemaSupport.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestDeltaLakeSchemaSupport.java',263,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTableSnapshot.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTableSnapshot.java',201,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTransactionLogParser.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTransactionLogParser.java',39,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointBuilder.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointBuilder.java',82,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java',241,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointWriter.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointWriter.java',443,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestTransactionLogTail.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestTransactionLogTail.java',74,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/statistics/BenchmarkDeltaLakeStatistics.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/statistics/BenchmarkDeltaLakeStatistics.java',154,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/statistics/TestDeltaLakeFileStatistics.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/statistics/TestDeltaLakeFileStatistics.java',197,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/Closer.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/Closer.java',86,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/DockerContainer.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/DockerContainer.java',26,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/DockerImages.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/DockerImages.java',24,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/DockerizedDataLake.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/DockerizedDataLake.java',95,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/DockerizedMinioDataLake.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/DockerizedMinioDataLake.java',128,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/MinioClient.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/MinioClient.java',236,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/MinioContainer.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/MinioContainer.java',66,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/PrintingLogConsumer.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/PrintingLogConsumer.java',50,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/SelectedPortWaitStrategy.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/SelectedPortWaitStrategy.java',102,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/TestingHadoop.java','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/TestingHadoop.java',270,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/bar/_delta_log/00000000000000000000.json','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/bar/_delta_log/00000000000000000000.json',3,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/bar/_delta_log/00000000000000000001.json','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/bar/_delta_log/00000000000000000001.json',2,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/bar/_delta_log/00000000000000000002.json','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/bar/_delta_log/00000000000000000002.json',2,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/bar/part-00000-70cbd30d-efb0-4090-a7b4-c1de8083743b-c000.snappy.parquet','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/bar/part-00000-70cbd30d-efb0-4090-a7b4-c1de8083743b-c000.snappy.parquet',0,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/bar/part-00000-cb64d459-76c9-486e-a259-9d160116bdd0-c000.snappy.parquet','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/bar/part-00000-cb64d459-76c9-486e-a259-9d160116bdd0-c000.snappy.parquet',0,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/README.md','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/README.md',12,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/.s3-optimization-0','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/.s3-optimization-0',0,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/.s3-optimization-1','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/.s3-optimization-1',0,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/.s3-optimization-2','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/.s3-optimization-2',0,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000000.crc','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000000.crc',1,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000000.json','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000000.json',3,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000001.crc','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000001.crc',1,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000001.json','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000001.json',2,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000002.crc','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000002.crc',1,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000002.json','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000002.json',2,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000003.crc','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000003.crc',1,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000003.json','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/_delta_log/00000000000000000003.json',2,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/number_partition=1/string_partition=__HIVE_DEFAULT_PARTITION__/part-00000-eea11d6e-8b50-408d-93a1-ec56027682aa.c000.snappy.parquet','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/number_partition=1/string_partition=__HIVE_DEFAULT_PARTITION__/part-00000-eea11d6e-8b50-408d-93a1-ec56027682aa.c000.snappy.parquet',0,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/number_partition=__HIVE_DEFAULT_PARTITION__/string_partition=__HIVE_DEFAULT_PARTITION__/part-00000-3181df7e-a84a-41a3-b42a-83f522a83a03.c000.snappy.parquet','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/number_partition=__HIVE_DEFAULT_PARTITION__/string_partition=__HIVE_DEFAULT_PARTITION__/part-00000-3181df7e-a84a-41a3-b42a-83f522a83a03.c000.snappy.parquet',0,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/number_partition=__HIVE_DEFAULT_PARTITION__/string_partition=partition_a/part-00000-92431a70-4cc6-482b-8ae0-bdd568557439.c000.snappy.parquet','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/default_partitions/number_partition=__HIVE_DEFAULT_PARTITION__/string_partition=partition_a/part-00000-92431a70-4cc6-482b-8ae0-bdd568557439.c000.snappy.parquet',0,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/foo/_delta_log/00000000000000000000.json','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/foo/_delta_log/00000000000000000000.json',3,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/foo/_delta_log/00000000000000000001.json','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/foo/_delta_log/00000000000000000001.json',2,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/foo/_delta_log/00000000000000000002.json','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/foo/_delta_log/00000000000000000002.json',2,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/foo/part-00000-6f261ad3-ab3a-45e1-9047-01f9491f5a8c-c000.snappy.parquet','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/foo/part-00000-6f261ad3-ab3a-45e1-9047-01f9491f5a8c-c000.snappy.parquet',0,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/foo/part-00000-f61316e9-b279-4efa-94c8-5ababdacf768-c000.snappy.parquet','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/foo/part-00000-f61316e9-b279-4efa-94c8-5ababdacf768-c000.snappy.parquet',0,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/insert_nested_nonlowercase_columns/README.md','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/insert_nested_nonlowercase_columns/README.md',9,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/insert_nested_nonlowercase_columns/_delta_log/00000000000000000000.crc','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/insert_nested_nonlowercase_columns/_delta_log/00000000000000000000.crc',1,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/insert_nested_nonlowercase_columns/_delta_log/00000000000000000000.json','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/insert_nested_nonlowercase_columns/_delta_log/00000000000000000000.json',3,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/insert_nested_nonlowercase_columns/_delta_log/00000000000000000001.crc','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/insert_nested_nonlowercase_columns/_delta_log/00000000000000000001.crc',1,0),('9956543e429419a268cfe20a47af7f7c47fa2398:plugin/trino-delta-lake/src/test/resources/databricks/insert_nested_nonlowercase_columns/_delta_log/00000000000000000001.json','2022-09-05 08:04:23.655','2022-09-05 08:04:23.655','','',0,'','9956543e429419a268cfe20a47af7f7c47fa2398','plugin/trino-delta-lake/src/test/resources/databricks/insert_nested_nonlowercase_columns/_delta_log/00000000000000000001.json',3,0) ON DUPLICATE KEY UPDATE `updated_at`='2022-09-05 08:04:23.981',`_raw_data_params`=VALUES(`_raw_data_params`),`_raw_data_table`=VALUES(`_raw_data_table`),`_raw_data_id`=VALUES(`_raw_data_id`),`_raw_data_remark`=VALUES(`_raw_data_remark`),`commit_sha`=VALUES(`commit_sha`),`file_path`=VALUES(`file_path`),`additions`=VALUES(`additions`),`deletions`=VALUES(`deletions`)"
time="2022-09-05 08:04:23" level=info msg=" [pipeline service] [pipeline #16] pipeline finished in 263208 ms: %!w(<nil>)"

```

### What you expected to happen

The trino project from github will succeed to be synced 

### How to reproduce

- Add github connection from https://github.com/trinodb/trino
- Add a buleprint for this connection/

### Anything else

_No response_

### Version

v0.12.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #3060: [Bug][Migrationscripts] use common and domainlayer for migrationscripts table model
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

image
image
image

There are many other places with similar problems.

### What you expected to happen

migrationscripts  table can only define in local or archived

### How to reproduce

see the code

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mappjzc**
# Summary
changed file_path from 255 to text
changed id fromcommitsha and path to commtsha and sha path
changed domainlayer and common to be archived

### Does this close any open issues?
Closes #2949 
Closes #3060 

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: plugins/jira/models/migrationscripts/20220505_rename_source_table.go [hunk 1]
```diff
@@ -43,7 +44,7 @@ func (JiraConnectionV010) TableName() string {
 type renameSourceTable struct{}
 
 func (*renameSourceTable) Up(ctx context.Context, db *gorm.DB) error {
-	err := db.Migrator().RenameTable(archived.JiraSource{}, JiraConnectionV010{})
+	err := db.Migrator().RenameTable(jiraArchived.JiraSource{}, JiraConnectionV010{})
```
Comment (warren830) [inline plugins/jira/models/migrationscripts/20220505_rename_source_table.go:47]: You can create a struct with tableName ‘jira_source’ instead of using jiraArchived

File: models/migrationscripts/20220913_commitfile_add_length.go [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+	Deletions int
+}
+
+func (CommitFileAddLengthBak) TableName() string {
+	return "commit_files_bak"
+}
+
+type addCommitFilePathLength struct{}
+
+func (*addCommitFilePathLength) Up(ctx context.Context, db *gorm.DB) errors.Error {
```
Comment (warren830) [inline models/migrationscripts/20220913_commitfile_add_length.go:59]: Please refer to plugins/gitlab/models/migrationscripts/20220906_fix_duration_to_float8.go

File: plugins/gitextractor/parser/repo.go [hunk 3]
```diff
@@ -329,7 +332,12 @@ func (r *GitRepo) storeCommitFilesFromDiff(commitSha string, diff *git.Diff, com
 		commitFile = new(code.CommitFile)
 		commitFile.CommitSha = commitSha
 		commitFile.FilePath = file.NewFile.Path
-		commitFile.Id = commitSha + ":" + file.NewFile.Path
+
+		// use commitSha and the sha256 of FilePath to create id
+		ShaFilePath := sha256.New()
+		ShaFilePath.Write([]byte(file.NewFile.Path))
+		commitFile.Id = commitSha + ":" + hex.EncodeToString(ShaFilePath.Sum(nil))
```
Comment (warren830) [inline plugins/gitextractor/parser/repo.go:339]: Can you comment why are you creating ShaFilePath like this?

File: plugins/gitextractor/parser/repo.go [hunk 4]
```diff
@@ -329,15 +332,20 @@ func (r *GitRepo) storeCommitFilesFromDiff(commitSha string, diff *git.Diff, com
 		commitFile = new(code.CommitFile)
 		commitFile.CommitSha = commitSha
 		commitFile.FilePath = file.NewFile.Path
-		commitFile.Id = commitSha + ":" + file.NewFile.Path
+
+		// use commitSha and the sha256 of FilePath to create id
+		shaFilePath := sha256.New()
+		shaFilePath.Write([]byte(file.NewFile.Path))
+		commitFile.Id = commitSha + ":" + hex.EncodeToString(shaFilePath.Sum(nil))
```
Comment (warren830) [inline plugins/gitextractor/parser/repo.go:339]: can you comment on why you are doing this?

File: models/migrationscripts/20220913_commitfile_add_length.go [hunk 5]
```diff
@@ -0,0 +1,191 @@
...
+	}
+	defer cursor.Close()
+
+	batch, err := helper.NewBatchSave(api.BasicRes, reflect.TypeOf(&CommitFileAddLength{}), 200)
+	if err != nil {
+		return errors.Default.Wrap(err, "error getting batch from table commit_file")
+	}
+
+	defer batch.Close()
+	for cursor.Next() {
```
Comment (warren830) [inline models/migrationscripts/20220913_commitfile_add_length.go:94]: Have you calculated how long does this whole process cost for a project like devlake?

File: plugins/gitextractor/parser/repo.go (hunk 4 above)
Comment (mappjzc) [reply plugins/gitextractor/parser/repo.go:339]: Because of issue https://github.com/apache/incubator-devlake/issues/2949
With some long path,the varchar(255) was not enough both ID and file_path
So we use the hash to compress the path in ID and add length of file_path.

File: models/migrationscripts/20220913_commitfile_add_length.go (hunk 5 above)
Comment (mappjzc) [reply models/migrationscripts/20220913_commitfile_add_length.go:94]: on two core host, 5200 times per second.

File: plugins/gitextractor/parser/repo.go (hunk 4 above)
Comment (warren830) [reply plugins/gitextractor/parser/repo.go:339]: please add `With some long path,the varchar(255) was not enough both ID and file_path
So we use the hash to compress the path in ID and add length of file_path.` to code

**Review by warren830 — APPROVED** [review]
LGTM

File: models/migrationscripts/20220913_commitfile_add_length.go [hunk 6]
```diff
@@ -0,0 +1,195 @@
...
+import (
+	"context"
+	"crypto/sha256"
+	"encoding/hex"
+	"reflect"
+	"strings"
+
+	"github.com/apache/incubator-devlake/errors"
+	"github.com/apache/incubator-devlake/models/migrationscripts/archived"
+	"github.com/apache/incubator-devlake/plugins/gitlab/api"
```
Comment (keon94) [inline models/migrationscripts/20220913_commitfile_add_length.go:29]: This is problematic. We shouldn't have a gitlab-specific under the models/migrationscripts. This is where the datasource-agnostic migrations take place.

If I were to turn off the gitlab plugin, I get a panic because [this line](https://github.com/apache/incubator-devlake/blob/e43b9d70203759ddbe97205f29aeb63106c50d34/plugins/gitlab/api/init.go#L30), which sets the BasicRes global variable, will not run. Either BasicRes has to be set independently of gitlab (different package outside of plugins/), or this migration needs to be moved to the [gitlab migrations package](https://github.com/apache/incubator-devlake/tree/main/plugins/gitlab/models/migrationscripts)
