### PR TITLE
fix: _raw_data_params are missing for some scope

### LINKED ISSUE #5582: [Bug] Remove data scopes from a project should not update table `boards`, `repos` or `cicd_scopes`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After I removed a TAPD workspace (a data scope) from a connection under a project, the `_raw_data_params` and `url` of another TAPD workspace are emptied.

image

### What do you expect to happen

After I removed a TAPD workspace (or any data scope) from a connection under a project, no data in table `boards` should be updated. 

### How to reproduce

N/A

### Anything else

_No response_

### Version

v0.18.0-alpha11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mindlesscloud**
### Summary
Fix #5582. During the execution of the blueprint, the scopes were created/updated twice, once at creating the pipeline and once at converting the boards/repos/cicd_scopes, the column `_raw_data_params` was not populated in the previous one. In this PR, we fix the issue by only creating/updating scopes once.

### Does this close any open issues?
Closes #5582 

### Screenshots
image

### CODE REVIEW

**Review by klesh — APPROVED** [review]
LGTM

File: backend/server/services/blueprint_makeplan_v200.go [hunk 1]
```diff
@@ -35,51 +35,26 @@ func GeneratePlanJsonV200(
...
 ) (plugin.PipelinePlan, errors.Error) {
-	// generate plan and collect scopes
-	plan, scopes, err := genPlanJsonV200(projectName, syncPolicy, sources, metrics, skipCollectors)
-	if err != nil {
-		return nil, err
-	}
-	// save scopes to database
-	if len(scopes) > 0 {
-		for _, scope := range scopes {
-			err = db.CreateOrUpdate(scope)
```
Comment (keon94) [inline backend/server/services/blueprint_makeplan_v200.go:46]: I don't understand this. Were the scopes here missing the "_raw_data_*" fields? That's odd

Comment (klesh) [reply backend/server/services/blueprint_makeplan_v200.go:46]: Because plugins would create a set of new domain layer scopes without the `_raw_data` fields, this line ruins whatever scope helper had taken care of on each run.
