### PR TITLE
fix(plugins): add status RUNNING

### LINKED ISSUE #3660: [Bug][CICD] Keep result as empty for unfinished cicd tasks/pipelines
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I just checked, all unfinished pipeline/tasks are also success 
At first, we tried to add `RUNNING` to indicate unfinished tasks/pipelines
But after deeper research, we found that for gitlab job, when it's unfinished, it has much more status like "created", "waiting_for_resource", "preparing", "pending", "running", "scheduled", jenkins also has a lot status to indicate unfinished.
More important, we found that in our original design, we should keep it empty.

### What do you expect to happen

keep their result as empty

### How to reproduce

none

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by warren830**
# Summary

use `RUNNING` to indicate that pipeline/task is unfinished
update e2e data for new status

### Does this close any open issues?
closes #3660

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: models/domainlayer/devops/cicd_pipeline.go [hunk 1]
```diff
@@ -53,6 +53,7 @@ func (CICDPipelineRelationship) TableName() string {
 
 const (
 	SUCCESS     = "SUCCESS"
+	RUNNING     = "RUNNING"
```
Comment (abeizn) [inline models/domainlayer/devops/cicd_pipeline.go:56]: What is the difference between RUNNING and IN_PROGRESS?

Comment (warren830) [reply models/domainlayer/devops/cicd_pipeline.go:56]: RUNNING is for result, IN_PROGRESS is for status

Comment (warren830) [reply models/domainlayer/devops/cicd_pipeline.go:56]: Maybe we can keep it as empty?

Comment (abeizn) [reply models/domainlayer/devops/cicd_pipeline.go:56]: > RUNNING is for result, IN_PROGRESS is for status

then i think RUNNING and IN_PROGRESS maybe written separately, so that users can understand.

**Review by abeizn — DISMISSED** [review]

**Review by abeizn — APPROVED** [review]
LGTM
