### PR TITLE
[fix-4772]: Python progress update crashes Go DevLake server

### LINKED ISSUE #4772: [Bug][pydevlake] Panic when running blueprint with large-ish amounts of data
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We have an internal release tool which I've written a plugin to scrape releases from. We're using the new `pydevlake` plugin stuff.

I've obfuscated some of the logs because the details aren't relevant to outside of where I work so I hope I've not removed anything useful.

When trigger a run of a blueprint (`curl -v -X 'POST' 'http://localhost:8080/blueprints/1/trigger'`) we end up with a `panic`:

```
...
time="2023-03-24 15:01:22" level=info msg=" [pipeline service] [pipeline #1] [task #1] [collectHopperReleases] DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=13 HTTP/1.1" 200 None"
time="2023-03-24 15:01:22" level=info msg=" [pipeline service] [pipeline #1] [task #1] [collectHopperReleases] DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=15 HTTP/1.1" 200 None"
time="2023-03-24 15:01:22" level=info msg=" [pipeline service] [pipeline #1] [task #1] [collectHopperReleases] DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=17 HTTP/1.1" 200 None"
time="2023-03-24 15:01:23" level=info msg=" [pipeline service] [pipeline #1] [task #1] [collectHopperReleases] DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=19 HTTP/1.1" 200 None"
time="2023-03-24 15:01:23" level=info msg=" [pipeline service] [pipeline #1] [task #1] [collectHopperReleases] DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=21 HTTP/1.1" 200 None"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10082d0aa]

goroutine 77 [running]:
github.com/apache/incubator-devlake/core/utils.scanOutputPipe.func1()
        /Users/sam/src/incubator-devlake/backend/core/utils/ipc.go:246 +0xea
created by github.com/apache/incubator-devlake/core/utils.StreamProcess
        /Users/sam/src/incubator-devlake/backend/core/utils/ipc.go:190 +0x34b
exit status 2
make[1]: *** [run] Error 1
make: *** [dev] Error 2
```

This works fine when run directly:

```
poetry run hopper/main.py collect "{\"db_url\": \"mysql://merico:merico@127.0.0.1:3306/lake\", \"scope\": {\"id\": \"test-http\", \"name\": \"test-http\"}, \"connection\": { \"id\": 1, \"name\": \"hopper\", \"endpoint\": \"https://***.net\", \"token\": \"${TOKEN}\"}}" releases 3>&1
DEBUG: Starting new HTTPS connection (1): ***.net:443
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=1 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=3 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=5 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=7 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=9 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=11 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=13 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=15 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=17 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=19 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=21 HTTP/1.1" 200 None
{"increment": 100, "current": 100}
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=23 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=23 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=23 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=25 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=27 HTTP/1.1" 200 None
DEBUG: https://***.net:443 "GET /api/apps/test-http/releases?page=29 HTTP/1.1" 200 None
...
```

I suspect what happens is [the message sent here](https://github.com/apache/incubator-devlake/blob/5f89c21181ca49cd10253078665a9124e030469a/backend/python/pydevlake/pydevlake/subtasks.py#L68-L71) isn't correctly handled on the go side of the IPC.

I've worked around this in the short term by setting `sync_point_interval` to something very large.

### What do you expect to happen

It should not panic the blueprint should run successfully.

### How to reproduce

See above.

### Anything else

Every time.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by keon94**
### Summary
* Adds a missing nil check on Go side which was causing crashes whenever Python would stream back a "RemoteProgress". This would get triggered if the number of records fetched on Python side was greater than 100 (or the default value of sync_point_interval in general) which is why we hadn't ran into it before in our light-weight tests. Tests updated to use larger datasets.
* Logic fix for progress counter which would always stay at 0 and possibly skip the last update.
* Some fixes to the Python remote debugger as I encountered issues during testing

### Does this close any open issues?
Closes #4772 

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/core/utils/ipc.go [hunk 1]
```diff
@@ -243,7 +243,9 @@ func scanOutputPipe(pipe io.ReadCloser, wg *sync.WaitGroup, onReceive func([]byt
 			src := scanner.Bytes()
 			data := make([]byte, len(src))
 			copy(data, src)
-			onReceive(data)
+			if onReceive != nil {
```
Comment (keon94) [inline backend/core/utils/ipc.go:246]: this missing nil check was the culprit

**Review by hezyin — APPROVED** [review]
LGTM
