### PR TITLE
fix: golangci-lint not works in CI

### LINKED ISSUE #2077: golangci-lint header linting doesn't seem to be working
## Describe the bug
File from https://github.com/apache/incubator-devlake/pull/2053/files#diff-f06f45811e3bd67de714c015e0f3efd9aac00b72618df90878a279f33209c090 has no head, but `golangci-lint` passed anyway.

## Expected behavior
`golangci-lint` should fail

## Screenshots
image

### PR DESCRIPTION
**Pull request by matrixji**
- run golangci-lint in lake-builder to ensure the toolchain is same as builder
- fix some header missing errors
- add //nolint and TODO for other errors(4 in total), which we may handle later
- enable gofmt in golangci-lint and add `make fmt` for format the whole project, this could keep us always with the same style.

fixes: #2077

Signed-off-by: Ji Bin <matrixji@live.com>

### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation
- [x] This PR is using a `label` (bug, feature etc.)
- [ ] My code is has necessary documentation (if appropriate)
- [ ] I have added any relevant tests
- [x] This section (**⚠️ &nbsp;&nbsp;Pre Checklist**) will be removed when submitting PR

# Summary

### Does this close any open issues?
Closes #2077 

### Screenshots
After this change, the lint jobs got:
```
Running [/github/home/golangci-lint-1.43.0-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  golangci-lint found no issues
  Ran golangci-lint in 119980ms
```

and previously:
```
  Running [/home/runner/golangci-lint-1.43.0-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildir: failed to load package git: could not load export data: no export data for \"github.com/libgit2/git2go/v33\""

  golangci-lint found no issues
  Ran golangci-lint in 20615ms
```

### Other Information
N/A

### CODE REVIEW

File: plugins/helper/default_task_context.go [hunk 1]
```diff
@@ -188,14 +188,14 @@ func (c *DefaultTaskContext) SubTaskContext(subtask string) (core.SubTaskContext
 	if run, ok := c.subtasks[subtask]; ok {
 		if run {
 			// now, create a sub task context if it didn't exist
-			c.mu.Lock()
+			c.defaultExecContext.mu.Lock()
```
Comment (likyh) [inline plugins/helper/default_task_context.go:191]: Why change this?

**Review by likyh — APPROVED** [review]
Good job~ LGTM. It's exactly only change base build container and run `golint-ci --fix`

File: plugins/helper/default_task_context.go (hunk 1 above)
Comment (matrixji) [reply plugins/helper/default_task_context.go:191]: It seems `structcheck`'s bug. It will report:
> plugins/helper/default_task_context.go:44:2: `mu` is unused (structcheck)
>        mu       sync.Mutex
>        ^


Maybe we could disable `structcheck `, it only checks unused fields, but it does not support  embedded struct


ref: https://gitlab.com/opennota/check#known-limitations
> structcheck doesn't handle embedded structs yet.

**Review by klesh — APPROVED** [review]
LGTM
