### PR TITLE
fix(framework): fix migration scripts

### LINKED ISSUE #3713: [Bug][Framework] migration failed from v0.12 to v0.14
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

According to #3537 , after migration, we found that _devlake_tasks.pipeline_id is not in accordance with _devlake_pipelines.id. 
There are two problems caused migration failed from v0.12 to 0.14
1. _devlake_tasks.id is not in accordance with pipeline.id
img_v2_40dbfb25-e994-4c4b-86ac-ce1a3ca9feag
 - previously, we migrate the whole table instead of changing columns
3. reported `_tool_jenkins_builds does not exist` 
img_v2_9f59a543-3db1-4f7e-b896-7ad1bc2117ag
 - when we are migrating jenkins build, we used cursor, and changed the table name of the cursor before we releasing it. 

### What do you expect to happen

None

### How to reproduce

none

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by warren830**
# Summary

In pr: https://github.com/apache/incubator-devlake/pull/3727, we fixed bugs for #3713 but just a hotfix for v0.14, this pr is to resolve the problem in main branch ,  in addition, for all fields with `datatypes.JSON`, we changed to `json.RawMessage` as pg would treat these two types with difference.

Lastly, we tested through the following steps:

1. deploy devlake v0.12 by docker-compose
2. created several blueprints and pipelines
3. collect jira, github, jenkins which were impacted in new data
4. shutdown v0.12 devlake
5. export all data
6. deploy 0.14 devlake and shutdown
7. deploy new code
8. check blueprints and pipelines through config-ui

Again, we also tested through the following steps which skipped step 4 above:
1. deploy devlake v0.12 by docker-compose
2. import the data which was exported at step 5 above
3. shutdown v0.12 devlake
5. deploy new code
6. check blueprints and pipelines through config-ui

### Does this close any open issues?
Closes #3713

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Review by klesh — COMMENTED** [review]
`TransformColumns` is packed with rename column operations.
I think we don't need to rename it manually.
The doc of `TransformColumns` is not very clear about that, we should provide an example to help developer understand the usage

**Comment by warren830** [comment]
> `TransformColumns` is packed with rename column operations. I think we don't need to rename it manually. The doc of `TransformColumns` is not very clear about that, we should provide an example to help developer understand the usage

Fixed, I will submit a pr for that

File: models/migrationscripts/20220903_encrypt_blueprint.go [hunk 1]
```diff
@@ -30,63 +28,59 @@ var _ core.MigrationScript = (*encryptBlueprint)(nil)
...
-	IsManual       bool            `json:"isManual"`
-	Settings       json.RawMessage `json:"settings" swaggertype:"array,string" example:"please check api: /blueprints/<PLUGIN_NAME>/blueprint-setting"`
-	archived.Model `swaggerignore:"true"`
+type BlueprintEncryption0904Before struct {
+	archived.Model
+	Plan     string
+	Settings string
+}
+
+func (BlueprintEncryption0904Before) TableName() string {
```
Comment (klesh) [inline models/migrationscripts/20220903_encrypt_blueprint.go:37]: No needed

File: models/migrationscripts/20220903_encrypt_blueprint.go [hunk 2]
```diff
@@ -30,63 +28,59 @@ var _ core.MigrationScript = (*encryptBlueprint)(nil)
...
+	return "_devlake_blueprints"
+}
+
+type BlueprintEncryption0904After struct {
```
Comment (klesh) [inline models/migrationscripts/20220903_encrypt_blueprint.go:41]: Looks like they are identical, we can use one struct instead

File: models/migrationscripts/20220903_encrypt_blueprint.go [hunk 3]
```diff
@@ -30,63 +28,59 @@ var _ core.MigrationScript = (*encryptBlueprint)(nil)
...
-	Name           string `json:"name" validate:"required"`
-	Mode           string `json:"mode" gorm:"varchar(20)" validate:"required,oneof=NORMAL ADVANCED"`
-	Enable         bool   `json:"enable"`
-	CronConfig     string `json:"cronConfig" format:"* * * * *" example:"0 0 * * 1"`
-	IsManual       bool   `json:"isManual"`
-	archived.Model `swaggerignore:"true"`
-	/* changed part */
-	Plan     string `json:"plan"`
-	Settings string `json:"settings"`
+func (BlueprintEncryption0904After) TableName() string {
```
Comment (klesh) [inline models/migrationscripts/20220903_encrypt_blueprint.go:47]: Not needed

File: models/migrationscripts/20220903_encrypt_blueprint.go [hunk 4]
```diff
@@ -30,63 +28,59 @@ var _ core.MigrationScript = (*encryptBlueprint)(nil)
...
+				Model:    src.Model,
+				Plan:     plan,
+				Settings: settings,
+			}, nil
 		},
 	)
+	if err != nil {
+		return err
+	}
+	_ = db.First(blueprint)
```
Comment (klesh) [inline models/migrationscripts/20220903_encrypt_blueprint.go:82]: Don't do it here, do it inside the helper.

File: models/migrationscripts/20220904_encrypt_pipeline.go [hunk 5]
```diff
@@ -18,81 +18,62 @@ limitations under the License.
...
+			return &PipelineEncryption0904After{
+				Model: src.Model,
+				Plan:  plan,
+			}, nil
 		},
 	)
+	if err != nil {
+		return err
+	}
+	_ = db.First(pipeline)
```
Comment (klesh) [inline models/migrationscripts/20220904_encrypt_pipeline.go:75]: Same as above

File: models/migrationscripts/20220903_encrypt_blueprint.go (hunk 1 above)
Comment (warren830) [reply models/migrationscripts/20220903_encrypt_blueprint.go]: fixed

File: models/migrationscripts/20220903_encrypt_blueprint.go (hunk 2 above)
Comment (warren830) [reply models/migrationscripts/20220903_encrypt_blueprint.go]: fixed

File: models/migrationscripts/20220903_encrypt_blueprint.go (hunk 4 above)
Comment (warren830) [reply models/migrationscripts/20220903_encrypt_blueprint.go]: fixed

File: models/migrationscripts/20220904_encrypt_pipeline.go (hunk 5 above)
Comment (warren830) [reply models/migrationscripts/20220904_encrypt_pipeline.go]: fixed

**Review by klesh — APPROVED** [review]
