### PR TITLE
fix: close pg conn

### LINKED ISSUE #4270: [Bug][StarRocks] PG connection not close
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

PG connection not close after StarRocks sync

### What do you expect to happen

PG connection close correctly

### How to reproduce

Sync data from to starrocks

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by long2ice**
### Summary
What does this PR do?

### Does this close any open issues?
Closes #4270 

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/plugins/starrocks/tasks/tasks.go [hunk 1]
```diff
@@ -186,16 +186,20 @@ func createTmpTable(starrocks *sql.DB, db dal.Dal, starrocksTable string, starro
...
+		if rowsInPostgres != nil {
+			rowsInPostgres.Close()
+		}
 	}()
 	for _, cm := range columnMetas {
 		name := cm.Name()
 		if name == updateColumn {
 			// check update column to detect skip or not
-			rows, err := db.Cursor(
+			rowsInPostgres, err = db.Cursor(
```
Comment (klesh) [inline backend/plugins/starrocks/tasks/tasks.go:202]: I believe we should close the cursor before assigning new one to the variable.

**Review by klesh — COMMENTED** [review]
I think https://github.com/apache/incubator-devlake/blob/a08a2e726753e59b493644c7e4910b3b5404d1aa/plugins/starrocks/tasks.go#L281 also has the same problem

**Review by abeizn — APPROVED** [review]
LGTM
