### PR TITLE
fix(framework): update code generator templates

### LINKED ISSUE #2640: [Bug][Generator] generator template needs to be updated
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Right now, our generator templates does not adapt to our new architect of plugins

### What you expected to happen

update them 

### How to reproduce

use code generator to create a new plugin

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by warren830**
closes #2640
# Summary

modify templates in package generator

### Does this close any open issues?
closes #2640

### Screenshots
image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: generator/template/plugin/tasks/api_client.go-template [hunk 1]
```diff
@@ -26,47 +26,59 @@ import (
...
 
 // TODO add what host would want to requist
-const ENDPOINT = "{{ .Endpoint }}"
 
-func New{{ .PluginName }}ApiClient(taskCtx core.TaskContext) (*helper.ApiAsyncClient, error) {
-	// load and process configuration
-	token := taskCtx.GetConfig("{{ .PLUGIN_NAME }}_TOKEN")
-	if token == "" {
-		println("invalid {{ .PLUGIN_NAME }}_TOKEN, but ignore this error now")
+import (
```
Comment (likyh) [inline generator/template/plugin/tasks/api_client.go-template:30]: import duplicate with Line 20~25

File: generator/template/plugin/tasks/api_client.go-template [hunk 2]
```diff
@@ -26,47 +26,59 @@ import (
...
+	"fmt"
+	"net/http"
+	"strconv"
+	"time"
+
+	"github.com/apache/incubator-devlake/plugins/{{ .pluginName }}/models"
```
Comment (likyh) [inline generator/template/plugin/tasks/api_client.go-template:36]: plugin_name

File: generator/template/plugin/tasks/api_client.go-template [hunk 3]
```diff
@@ -26,47 +26,59 @@ import (
...
+
+	"github.com/apache/incubator-devlake/plugins/core"
+	"github.com/apache/incubator-devlake/plugins/helper"
+)
+
+func New{{ .PluginName }}ApiClient(taskCtx core.TaskContext, connection *models.{{ .PluginName }}Connection) (*helper.ApiAsyncClient, error) {
```
Comment (likyh) [inline generator/template/plugin/tasks/api_client.go-template:42]: Must the new plugin use the connection? Is there any simple way to deal with it?

File: generator/cmd/create_plugin.go [hunk 4]
```diff
@@ -131,6 +131,7 @@ Type in what the name of plugin is, then generator will create a new plugin in p
 			// read template
 			templates = map[string]string{
 				`plugin_main.go`:      util.ReadTemplate("generator/template/plugin/plugin_main_with_api_client.go-template"),
+				`impl/impl.go`:        util.ReadTemplate("generator/template/plugin/impl/impl.go-template"),
```
Comment (likyh) [inline generator/cmd/create_plugin.go:134]: impl_with_api_client.go-template  ?

File: generator/template/plugin/tasks/api_client.go-template [hunk 5]
```diff
@@ -26,47 +26,59 @@ import (
...
-	// set token
-	if token != "" {
-		apiClient.SetHeaders(map[string]string{
-			"Authorization": fmt.Sprintf("Bearer %v", token),
-		})
+	// create rate limit calculator
+	rateLimiter := &helper.ApiRateLimitCalculator{
+		UserRateLimitPerHour: connection.RateLimitPerHour,
+		DynamicRateLimit: func(res *http.Response) (int, time.Duration, error) {
+			rateLimitHeader := res.Header.Get("RateLimit-Limit")
```
Comment (likyh) [inline generator/template/plugin/tasks/api_client.go-template:62]: Not all API has the header `RateLimit-Limit`.

File: generator/template/plugin/impl/impl.go-template [hunk 6]
```diff
@@ -0,0 +1,123 @@
...
+limitations under the License.
+*/
+
+package impl
+
+import (
+	"github.com/apache/incubator-devlake/migration"
+	"github.com/apache/incubator-devlake/plugins/core"
+    "github.com/apache/incubator-devlake/plugins/helper"
+    "github.com/apache/incubator-devlake/plugins/{{ .plugin_name }}/api"
```
Comment (likyh) [inline generator/template/plugin/impl/impl.go-template:24]: there is no `api`/`models`/`migrationscripts` package

**Review by likyh — CHANGES_REQUESTED** [review]

File: generator/template/plugin/tasks/api_client.go-template (hunk 2 above)
Comment (warren830) [reply generator/template/plugin/tasks/api_client.go-template:36]: fixed

File: generator/template/plugin/tasks/api_client.go-template (hunk 1 above)
Comment (warren830) [reply generator/template/plugin/tasks/api_client.go-template:30]: fixed

File: generator/cmd/create_plugin.go [hunk 7]
```diff
@@ -112,30 +113,21 @@ Type in what the name of plugin is, then generator will create a new plugin in p
...
-
+			versionTimestamp := time.Now().Format(`20060102`)
+			values[`Date`] = versionTimestamp
 			// read template
 			templates = map[string]string{
-				`plugin_main.go`:      util.ReadTemplate("generator/template/plugin/plugin_main_with_api_client.go-template"),
-				`tasks/api_client.go`: util.ReadTemplate("generator/template/plugin/tasks/api_client.go-template"),
-				`tasks/task_data.go`:  util.ReadTemplate("generator/template/plugin/tasks/task_data_with_api_client.go-template"),
+				fmt.Sprintf(`%s.go`, pluginName): util.ReadTemplate("generator/template/plugin/plugin_main_with_api_client.go-template"),
+				`impl/impl.go`:                   util.ReadTemplate("generator/template/plugin/impl/impl_with_api_client.go-template"),
```
Comment (likyh) [inline generator/cmd/create_plugin.go:121]: it also related with: https://github.com/apache/incubator-devlake/blob/main/generator/cmd/create_collector.go#L138

File: generator/template/plugin/impl/impl_with_api_client.go-template [hunk 8]
```diff
@@ -0,0 +1,123 @@
...
+
+package impl
+
+import (
+	"fmt"
+	"github.com/apache/incubator-devlake/migration"
+	"github.com/apache/incubator-devlake/plugins/core"
+    "github.com/apache/incubator-devlake/plugins/{{ .plugin_name }}/api"
+    "github.com/apache/incubator-devlake/plugins/{{ .plugin_name }}/models"
+    "github.com/apache/incubator-devlake/plugins/{{ .plugin_name }}/models/migrationscripts"
```
Comment (likyh) [inline generator/template/plugin/impl/impl_with_api_client.go-template:26]: let's use a tab instead of 4 spaces.

File: generator/template/plugin/models/connection.go-template [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+}
+
+// Using User because it requires authentication.
+type ApiUserResponse struct {
+	Id   int
+	Name string `json:"name"`
+}
+
+func ({{ .PluginName }}Connection) TableName() string {
+	return "_tool_{{ .plugin-name }}_connections"
```
Comment (likyh) [inline generator/template/plugin/models/connection.go-template:49]: Instead of `plugin-name`, it should be `plugin_name`

File: generator/template/plugin/plugin_main_with_api_client.go-template [hunk 10]
```diff
@@ -18,70 +18,13 @@ limitations under the License.
 package main
 
 import (
-	"github.com/apache/incubator-devlake/plugins/core"
-	"github.com/apache/incubator-devlake/plugins/{{ .pluginName }}/tasks"
+	"github.com/apache/incubator-devlake/plugins/{{ .PluginName }}/impl"
```
Comment (likyh) [inline generator/template/plugin/plugin_main_with_api_client.go-template:21]: plugin_name

File: generator/template/plugin/impl/impl_with_api_client.go-template [hunk 11]
```diff
@@ -0,0 +1,123 @@
...
+        "connections/:connectionId": {
+            "GET":    api.GetConnection,
+            "PATCH":  api.PatchConnection,
+            "DELETE": api.DeleteConnection,
+        },
+    }
+}
+
+func (plugin {{ .PluginName }}) MakePipelinePlan(connectionId uint64, scope []*core.BlueprintScopeV100) (core.PipelinePlan, error) {
+	return api.MakePipelinePlan(plugin.SubTaskMetas(), connectionId, scope)
```
Comment (likyh) [inline generator/template/plugin/impl/impl_with_api_client.go-template:113]: where is the MakePipelinePlan?

File: generator/template/plugin/api/connection.go-template [hunk 12]
```diff
@@ -0,0 +1,155 @@
...
+	"github.com/apache/incubator-devlake/plugins/helper"
+	"github.com/apache/incubator-devlake/plugins/{{ .PluginName }}/models"
+	"github.com/mitchellh/mapstructure"
+)
+
+//TODO Please modify the following code to fit your needs
+func TestConnection(input *core.ApiResourceInput) (*core.ApiResourceOutput, error) {
+	// decode
+	var err error
+	var connection models.TestConnectionRequest
```
Comment (likyh) [inline generator/template/plugin/api/connection.go-template:36]: Where is `TestConnectionRequest` ?

File: generator/template/plugin/api/connection.go-template [hunk 13]
```diff
@@ -0,0 +1,155 @@
...
+
+import (
+	"context"
+	"fmt"
+	"net/http"
+	"time"
+
+	"github.com/apache/incubator-devlake/plugins/core"
+	"github.com/apache/incubator-devlake/plugins/helper"
+	"github.com/apache/incubator-devlake/plugins/{{ .PluginName }}/models"
```
Comment (likyh) [inline generator/template/plugin/api/connection.go-template:28]: plugin_name

File: generator/template/plugin/api/blueprint.go-template [hunk 14]
```diff
@@ -0,0 +1,69 @@
...
+*/
+
+package api
+
+import (
+	"encoding/json"
+
+	"github.com/apache/incubator-devlake/plugins/core"
+	"github.com/apache/incubator-devlake/plugins/helper"
+	"github.com/apache/incubator-devlake/plugins/{{ .plugin-name }}/tasks"
```
Comment (likyh) [inline generator/template/plugin/api/blueprint.go-template:25]: plugin_name

File: generator/template/plugin/impl/impl_with_api_client.go-template [hunk 15]
```diff
@@ -0,0 +1,123 @@
...
+
+    return &tasks.{{ .PluginName }}TaskData{
+        Options:   op,
+        ApiClient: apiClient,
+    }, nil
+}
+
+// PkgPath information lost when compiled as plugin(.so)
+func (plugin {{ .PluginName }}) RootPkgPath() string {
+	return "github.com/apache/incubator-devlake/plugins/{{ .plugin-name }}"
```
Comment (likyh) [inline generator/template/plugin/impl/impl_with_api_client.go-template:88]: plugin_name

File: generator/template/plugin/api/blueprint.go-template [hunk 16]
```diff
@@ -0,0 +1,69 @@
...
+			return nil, err
+		}
+		// subtasks
+		subtasks, err := helper.MakePipelinePlanSubtasks(subtaskMetas, scopeElem.Entities)
+		if err != nil {
+			return nil, err
+		}
+		plan[i] = core.PipelineStage{
+			{
+				Plugin:   "{{ .plugin-name }}",
```
Comment (likyh) [inline generator/template/plugin/api/blueprint.go-template:62]: plugin_name

File: generator/template/plugin/api/blueprint.go-template [hunk 17]
```diff
@@ -0,0 +1,69 @@
+/*
```
Comment (likyh) [inline generator/template/plugin/api/blueprint.go-template:1]: This file seems not used.

File: generator/cmd/create_plugin.go [hunk 18]
```diff
@@ -112,30 +113,21 @@ Type in what the name of plugin is, then generator will create a new plugin in p
 		values := map[string]string{}
 		templates := map[string]string{}
 		if withApiClient == `Yes` {
```
Comment (likyh) [inline generator/cmd/create_plugin.go:115]: change `withApiClient` to `generateCompletePlugin` or other appropriate name?

**Review by likyh — CHANGES_REQUESTED** [review]

File: generator/cmd/create_plugin.go (hunk 18 above)
Comment (warren830) [reply generator/cmd/create_plugin.go:115]: good idea

File: generator/template/plugin/api/blueprint.go-template (hunk 17 above)
Comment (warren830) [reply generator/template/plugin/api/blueprint.go-template:1]: fixed

**Comment by likyh** [comment]
LGTM

**Review by abeizn — APPROVED** [review]
LGTM
