### PR TITLE
fix: fix if gitlab api response with no type or issuetype

### LINKED ISSUE #2555: [Bug][gitlab] api return with no type and not issue type filed for any typeof issue on gitlab 13.5.3
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the code
image
We have check if the issueType is issue.
But at the api response of gitlab 13.5.3 , there was no type info, as follow.
image

even the issue is created with type issue setting.
image

and because of that, the issue table was empty.

### What you expected to happen

Extract issue data success.

### How to reproduce

1.install gitlab version 13.5.3
2.create new issue.
3.collect it,or use api to visit it.

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mappjzc**
# Summary
Check if it setting the type or issue type before value checking.

### Does this close any open issues?
close #2555 

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: plugins/gitlab/tasks/issue_extractor.go [hunk 1]
```diff
@@ -186,17 +186,23 @@ func ExtractApiIssues(taskCtx core.SubTaskContext) error {
 		Extract: func(row *helper.RawData) ([]interface{}, error) {
 			body := &IssuesResponse{}
 			err := json.Unmarshal(row.Data, body)
+			fmt.Println(string(row.Data))
```
Comment (klesh) [inline plugins/gitlab/tasks/issue_extractor.go:189]: Please remove this

File: plugins/gitlab/tasks/issue_extractor.go [hunk 2]
```diff
@@ -186,17 +186,23 @@ func ExtractApiIssues(taskCtx core.SubTaskContext) error {
...
 
 			if body.ProjectId == 0 {
 				return nil, nil
 			}
-			//If this is not Issue, ignore
-			if body.IssueType != "ISSUE" && body.Type != "ISSUE" {
-				return nil, nil
+
+			//If this have the info about Type or IssueType
+			if body.IssueType != "" || body.Type != "" {
```
Comment (klesh) [inline plugins/gitlab/tasks/issue_extractor.go:199]: So, does it mean that it MUST be an `issue` if any of these fields is missing?

**Review by klesh — APPROVED** [review]
LGTM
