### PR TITLE
fix(jira): change filter for jira_issues

### LINKED ISSUE #2386: [Bug][jira] `board_issues` contains relationships between different `connections`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

image

### What you expected to happen

This kind of relationship should not exist

### How to reproduce

Not sure

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by warren830**
# Summary

Previously, we select * from `_tool_jira_issues` and join `board_issues` with condition `_tool_jira_board_issues.connction_id = ?`
This will cause us to get all data from _tool_jira_issues with different connection_id but same issue_id.
So we change the condition to `_tool_jira_issues.connection_id = ?`

### Does this close any open issues?
closes #2386

### Screenshots
image
image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: plugins/jira/tasks/issue_convertor.go [hunk 1]
```diff
@@ -50,7 +50,7 @@ func ConvertIssues(taskCtx core.SubTaskContext) error {
 		dal.From(jiraIssue),
 		dal.Join("left join _tool_jira_board_issues on _tool_jira_board_issues.issue_id = _tool_jira_issues.issue_id"),
 		dal.Where(
-			"_tool_jira_board_issues.connection_id = ? AND _tool_jira_board_issues.board_id = ?",
+			"_tool_jira_issues.connection_id = ? AND _tool_jira_board_issues.board_id = ?",
```
Comment (klesh) [inline plugins/jira/tasks/issue_convertor.go:53]: This doesn't seem legit.
We should modify the `Join` condition rather than `Where` condition

Comment (warren830) [reply plugins/jira/tasks/issue_convertor.go]: fixed

**Review by klesh — APPROVED** [review]
LGTM
