### PR TITLE
fix: stuck tasks

### LINKED ISSUE #5569: [Bug][framework] subtasks seem to get stuck forever
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

subtasks seem to get stuck forever
image

### What do you expect to happen

Task execution should succeed or fail and should not get stuck

### How to reproduce

- setup DevLake@v0.18.0-alpha10
- create a blueprint to collect data from Jira
- run the blueprint

### Anything else

_No response_

### Version

v0.18.0-alpha10

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mindlesscloud**
### Summary
Fix #5569, This bug is due to not being careful enough with the use of Mutex

### Does this close any open issues?
Closes #5569 

### Screenshots
image

### CODE REVIEW

File: backend/helpers/pluginhelper/api/batch_save.go [hunk 1]
```diff
@@ -102,17 +102,21 @@ func (c *BatchSave) Add(slot interface{}) errors.Error {
 	c.current++
 	// flush out into database if max outed
 	if c.current == c.size {
-		return c.Flush()
+		return c.flushWithoutLocking()
 	} else if c.current%100 == 0 {
 		c.log.Debug("batch save current: %d", c.current)
 	}
 	return nil
 }
```
Comment (keon94) [inline backend/helpers/pluginhelper/api/batch_save.go:111]: the comments should say "maxed out" not "max outed"

File: backend/helpers/pluginhelper/api/batch_save.go [hunk 2]
```diff
@@ -132,8 +136,10 @@ func (c *BatchSave) Flush() errors.Error {
```
Comment (keon94) [inline backend/helpers/pluginhelper/api/batch_save.go:136]: "flush" not "flash"

**Review by klesh — APPROVED** [review]
