### PR TITLE
Fix cancelling pipeline doesn't support pending(TASK_CREATED/TASK_RERUN) records

### LINKED ISSUE #3825: [Bug][core] cannot cancel pipelines with status 'TASK_CREATED'
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I use api `DELETE /pipelines/:id` to cancal pipelines with status 'TASK_CREATED'. But it not works.

### What do you expect to happen

The target pipeline should be cancelled.

### How to reproduce

Create some pipelines, the latter ones will be put in queue (with status 'TASK_CREATED'. Then call api `DELETE /pipelines/:id` to cancel it, but it not works.

### Anything else

_No response_

### Version

v0.14.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by klesh**
### Summary
Fix cancelling pipeline doesn't support pending(TASK_CREATED/TASK_RERUN) records

### Does this close any open issues?
Closes #3825 

### Screenshots
with this fix, when pipeline 6 is running and 7 is pending, after requesting `DELETE /pipelines/7`, the following screenshot shows pipeline 7 has been cancelled successfully.
image

### CODE REVIEW

File: services/pipeline.go [hunk 1]
```diff
@@ -348,6 +348,32 @@ func NotifyExternal(pipelineId uint64) errors.Error {
...
+	pipeline := &models.DbPipeline{}
+	err := db.First(pipeline, pipelineId).Error
+	if err != nil {
+		return errors.BadInput.New("pipeline not found")
+	}
+	if pipeline.Status == models.TASK_CREATED || pipeline.Status == models.TASK_RERUN {
+		pipeline.Status = models.TASK_CANCELLED
+		result := db.Save(pipeline)
+		if result.Error != nil {
+			println(result.Error.Error())
```
Comment (likyh) [inline services/pipeline.go:363]: delete debug code

**Review by likyh — APPROVED** [review]
