### PR TITLE
fix: jobs miss type field

### LINKED ISSUE #2565: [Bug][domain] jobs miss type field
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

domain layer jobs  miss `type` field, unable to confirm the specific type of jenkins job, e.g. folder or job.

### What you expected to happen

 jobs add `type` field

### How to reproduce

View the database jobs table structure

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by abeizn**
# Summary
jobs add `type` field.

### Does this close any open issues?
fix #2565

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: models/migrationscripts/register.go [hunk 1]
```diff
@@ -28,5 +28,6 @@ func All() []migration.Script {
 		new(updateBlueprintMode),
 		new(renameTasksToPlan),
 		new(addDomainTables),
+		new(addTypeField),
```
Comment (mappjzc) [inline models/migrationscripts/register.go:31]: it might should add to /plugins/jenkins/models/migrationscripts

File: plugins/jenkins/tasks/job_convertor.go [hunk 2]
```diff
@@ -71,6 +71,7 @@ func ConvertJobs(taskCtx core.SubTaskContext) error {
 					Id: jobIdGen.Generate(jenkinsJob.ConnectionId, jenkinsJob.Name),
 				},
 				Name: jenkinsJob.Name,
+				Type: jenkinsJob.Class,
```
Comment (mappjzc) [inline plugins/jenkins/tasks/job_convertor.go:74]: maybe we can keep the filed name `class`

**Review by mappjzc — APPROVED** [review]

File: models/migrationscripts/register.go (hunk 1 above)
Comment (abeizn) [reply models/migrationscripts/register.go:31]: no, it is domain layer
