### PR TITLE
fix(tapd): fix json tag for story and task

### LINKED ISSUE #4419: [Bug][Tapd] Wrong json tag in story and task model
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

tapd use custom_field_six, custom_field_seven, custom_field_eight in their story and task api response, but we used custom_field_6-8,

### What do you expect to happen

fix json tag to adapt tapd

### How to reproduce

collect story and task and check data

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by warren830**
### Summary
This pr changed json tag for story and task model.
Already fixed and tested in #4415 

### Does this close any open issues?
Closes #4419 

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/plugins/tapd/models/migrationscripts/archived/story.go [hunk 1]
```diff
@@ -82,9 +82,9 @@ type TapdStory struct {
 	CustomFieldThree string `json:"custom_field_three" gorm:"type:text"`
 	CustomFieldFour  string `json:"custom_field_four" gorm:"type:text"`
 	CustomFieldFive  string `json:"custom_field_five" gorm:"type:text"`
-	CustomField6     string `json:"custom_field_6" gorm:"type:text"`
-	CustomField7     string `json:"custom_field_7" gorm:"type:text"`
-	CustomField8     string `json:"custom_field_8" gorm:"type:text"`
+	CustomField6     string `json:"custom_field_six" gorm:"type:text"`
+	CustomField7     string `json:"custom_field_seven" gorm:"type:text"`
+	CustomField8     string `json:"custom_field_eight" gorm:"type:text"`
 	CustomField9     string `json:"custom_field_9" gorm:"type:text"`
```
Comment (abeizn) [inline backend/plugins/tapd/models/migrationscripts/archived/story.go:88]: 9， 10， 11  need ?

**Review by abeizn — APPROVED** [review]
lgtm
