### PR TITLE
Fix jira 400 error on collecting account

### LINKED ISSUE #4302: [Bug][Jira] Http 400 bad request errors when GET api/2/user within collectAccounts subtask
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Jira Cloud users report Jira tasks failures due to `collectAccounts` subtask failures.

`collectAccounts` got HTTP 400 bad request error when GET api/2/user, the error message is

```
Wraps: (2) Http DoAsync error calling [GET api/2/user]. Response: {"errorMessages":["The 'accountId' query parameter needs to be provided"],"errors":{}} (400)
```

See below for an example failure log:

```
ime="2023-02-02 19:52:18" level=info msg=" [pipeline service] [pipeline #132] [task #18366] executing subtask extractIssues"
time="2023-02-02 19:52:18" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [extractIssues] extract Issues, connection_id=1, board_id=36"
time="2023-02-02 19:52:18" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [extractIssues] get data from _raw_jira_api_issues where params={"ConnectionId":1,"BoardId":36} and got 654"
time="2023-02-02 19:52:18" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [extractIssues] finished records: 1"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [extractIssues] finished records: 1000"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [extractIssues] finished records: 2000"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [extractIssues] finished records: 3000"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [extractIssues] finished records: 4000"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [extractIssues] finished records: 5000"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [extractIssues] finished records: 6000"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [extractIssues] finished records: 7000"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] finished step: 8 / 28"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] executing subtask collectIssueChangelogs"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [collectIssueChangelogs] start api collection"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [collectIssueChangelogs] end api collection without error"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] finished step: 9 / 28"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] executing subtask extractIssueChangelogs"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [extractIssueChangelogs] get data from _raw_jira_api_issue_changelogs where params={"ConnectionId":1,"BoardId":36} and got 293"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [extractIssueChangelogs] finished records: 1"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [extractIssueChangelogs] finished records: 1000"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] finished step: 10 / 28"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] executing subtask collectAccounts"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [collectAccounts] collect account"
time="2023-02-02 19:52:19" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [collectAccounts] start api collection"
time="2023-02-02 19:52:20" level=warning msg=" [pipeline service] [pipeline #132] [task #18366] retry #0 calling api/2/user
	caused by: Http DoAsync error calling [GET api/2/user]. Response: {"errorMessages":["The 'accountId' query parameter needs to be provided"],"errors":{}} (400)"
time="2023-02-02 19:52:20" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [collectAccounts] finished records: 1"
time="2023-02-02 19:52:23" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [collectAccounts] finished records: 10"
time="2023-02-02 19:52:25" level=warning msg=" [pipeline service] [pipeline #132] [task #18366] retry #1 calling api/2/user
	caused by: Http DoAsync error calling [GET api/2/user]. Response: {"errorMessages":["The 'accountId' query parameter needs to be provided"],"errors":{}} (400)"
time="2023-02-02 19:52:26" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [collectAccounts] finished records: 18"
time="2023-02-02 19:52:30" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [collectAccounts] finished records: 27"
time="2023-02-02 19:52:30" level=warning msg=" [pipeline service] [pipeline #132] [task #18366] retry #2 calling api/2/user
	caused by: Http DoAsync error calling [GET api/2/user]. Response: {"errorMessages":["The 'accountId' query parameter needs to be provided"],"errors":{}} (400)"
time="2023-02-02 19:52:33" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [collectAccounts] finished records: 35"
time="2023-02-02 19:52:35" level=error msg=" [pipeline service] [pipeline #132] [task #18366] retry exceeded 3 times calling api/2/user (400)
	Wraps: (2) Http DoAsync error calling [GET api/2/user]. Response: {"errorMessages":["The 'accountId' query parameter needs to be provided"],"errors":{}} (400)
	Error types: (1) *hintdetail.withDetail (2) *errors.errorString"
time="2023-02-02 19:52:36" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [collectAccounts] finished records: 43"
time="2023-02-02 19:52:39" level=info msg=" [pipeline service] [pipeline #132] [task #18366] [collectAccounts] finished records: 52"
time="2023-02-02 19:52:40" level=error msg=" [pipeline service] [pipeline #132] [task #18366] subtask collectAccounts ended unexpectedly
	Wraps: (2) retry exceeded 3 times calling api/2/user (400)
	Error types: (1) *hintdetail.withDetail (2) *errors.errorString"
```

### What do you expect to happen

No HTTP 400 bad request error.

### How to reproduce

I wasn't able to reproduce this error with my Jira instance/board. So it may have to do with the user's Jira configuration, token permission, board configuration, etc.

Users are on v0.15.0-rc5.

### Anything else

_No response_

### Version

v0.15.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mindlesscloud**
### Summary
Fix the bug reported in #4302, which is triggered by requesting the `user` API `/rest/api/2/user` with an empty `accountId` parameter. This PR includes the following modification:
- save the `account` only if the accountId is not empty
- make sure the `accountId` is not empty when sending the HTTP request
- add e2e test

### Does this close any open issues?
Closes #4302

### CODE REVIEW

File: backend/plugins/jira/tasks/issue_changelog_extractor.go [hunk 1]
```diff
@@ -69,12 +69,17 @@ func ExtractIssueChangelogs(taskCtx plugin.SubTaskContext) errors.Error {
 			// this is crucial for incremental update
 			cl.IssueUpdated = &input.UpdateTime
 			// collect changelog / user inforation
-			result = append(result, cl, user)
+			result = append(result, cl)
+			if user != nil {
```
Comment (abeizn) [inline backend/plugins/jira/tasks/issue_changelog_extractor.go:73]: Is there still need user.AccountId != ""？

Comment (mindlesscloud) [reply backend/plugins/jira/tasks/issue_changelog_extractor.go:73]: If the `user` is not nil, the struct field `AccountId` will not be empty.

**Review by abeizn — APPROVED** [review]
LGTM
