### PR TITLE
fix(config-ui): transformation not updating correctly when switching boards

### LINKED ISSUE #3295: [Bug][config-ui] add board but type mapping is wrong when edit jira blueprint
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

image

### What you expected to happen

new boards have correct type mapping. It should equal user select.

### How to reproduce

1. find an existing blueprint with jira.
2. add a board in jira
3. select an issue type for bugs
4. save
5. look at the body of request

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mintsweet**
# Summary

transformation not updating correctly when switching boards.

### Does this close any open issues?
Closes #3295

### Screenshots
Nothing.

### Other Information
Nothing.

### CODE REVIEW

File: config-ui/src/pages/configure/settings/jira.jsx [hunk 1]
```diff
@@ -177,58 +177,35 @@ export default function JiraSettings(props) {
...
-    console.log('>> CONN SETTINGS OBJECT ', connection)
-    if (connection && connection.id) {
-      // Parse Type Mappings (V2)
-      // setStatusMappings([])
-    }
-  }, [connection])
+    setTypeMappingAll((ma) => ({
+      ...ma,
+      ...(typeMappingIncident || [])
+        .map((r) => createTypeMapObject(r.value, MAPPING_TYPES.Requirement))
```
Comment (e2corporation) [inline config-ui/src/pages/configure/settings/jira.jsx:192]: Is this supposed to be `MAPPING_TYPES.Incident` ?

File: config-ui/src/pages/configure/settings/jira.jsx [hunk 2]
```diff
@@ -177,58 +177,35 @@ export default function JiraSettings(props) {
...
-      console.log(
-        '>> FINAL MAPPING OBJECTS FOR API REQUEST...',
-        MappingTypeObjects
-      )
-    }
-  }, [typeMappingBug, typeMappingIncident, typeMappingRequirement])
+    setTypeMappingAll((ma) => ({
+      ...ma,
+      ...(typeMappingBug || [])
+        .map((r) => createTypeMapObject(r.value, MAPPING_TYPES.Requirement))
```
Comment (e2corporation) [inline config-ui/src/pages/configure/settings/jira.jsx:183]: Is this supposed to be MAPPING_TYPES.Bug ?

File: config-ui/src/pages/configure/settings/jira.jsx [hunk 3]
```diff
@@ -177,58 +177,35 @@ export default function JiraSettings(props) {
...
+  }, [typeMappingIncident])
+
+  useEffect(() => {
+    setTypeMappingAll((ma) => ({
+      ...ma,
+      ...(typeMappingRequirement || [])
+        .map((r) => createTypeMapObject(r.value, MAPPING_TYPES.Requirement))
+        .reduce((c, p) => ({ ...c, ...p }), {})
+    }))
+  }, [typeMappingRequirement])
```
Comment (likyh) [inline config-ui/src/pages/configure/settings/jira.jsx:204]: why not merge to one `useEffect`?     Will it add more than one duplicate for typeMappingXXX in typeMappingAll

Comment (mintsweet) [reply config-ui/src/pages/configure/settings/jira.jsx:204]: Independent dependencies allow **react** to distinguish which needs to be recalculated. If merged, individual changes will cause the whole to be recalculated, wasting performance.

Comment (e2corporation) [reply config-ui/src/pages/configure/settings/jira.jsx:204]: Effects run asynchronously, there's a reason why the existing logic was using 1 Effect in the first place, `typeMappingAll` may encounter collisions as a result. The 3 separate requirement groups should all be processed at the same time, not separately.

Comment (e2corporation) [reply config-ui/src/pages/configure/settings/jira.jsx:204]: Type Mappings have been running stable inside **One** Effect since this PR https://github.com/apache/incubator-devlake/pull/676

Comment (mintsweet) [reply config-ui/src/pages/configure/settings/jira.jsx:204]: The reason why this bug occurs is because when the board is switched, the three dependencies have not changed.

Comment (mintsweet) [reply config-ui/src/pages/configure/settings/jira.jsx:204]: Of course, merging them together can work, but sometimes they do not change at the same time, and the other two variables will also change, which is not necessary. Splitting them can monitor their own related content changes so that changes among them Previously do not cause additional content to be recalculated.

Comment (e2corporation) [reply config-ui/src/pages/configure/settings/jira.jsx:204]: @mintsweet In the past I recalled using 3 separate Effects only to find out that it caused a sync-issue on the UI when selectors were used rapidly, resulting in `typeMappingAll` being overwritten. I am willing to try 3 separate Effects again, assuming it directly addresses the bug reported on issue 3295.

Comment (likyh) [reply config-ui/src/pages/configure/settings/jira.jsx:204]: It resolves #3295 but #3294 exists.  I think we can merge it and I'll try to refactor here to delete `configuredBoard` in the detail page and resolve #3294

**Review by likyh — APPROVED** [review]
It looks approved if it works. And I want to change it in #3371. So merged.
