### PR TITLE
fix: unauthorized return 400 instead of 401

### LINKED ISSUE #5068: [Bug][config-ui] config-ui reset login when TestConnection failed and return 401
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Because the TestConnection returns the status code 401,
The Config-ui will reset the login state.

It made the user need to rewrite the username and password to config-ui again and again in each TestConnection 401 code return.
image

This is a very bad experience for users.

### What do you expect to happen

The user needn't rewrite there username and password to config-ui anymore after the TestConnection failed.

### How to reproduce

test any connection with wrong token.

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mappjzc**
### Summary
Because of the 401 error will reset the config-UI login.
So It changed all 401 to 400.

### Does this close any open issues?
Closes #5068 

### Screenshots
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Review by abeizn — APPROVED** [review]
LGTM

File: backend/plugins/teambition/api/connection.go [hunk 1]
```diff
@@ -70,7 +74,10 @@ func TestConnection(input *plugin.ApiResourceInput) (*plugin.ApiResourceOutput,
 		return nil, err
 	}
 	if resBody.Code != http.StatusOK {
```
Comment (likyh) [inline backend/plugins/teambition/api/connection.go:76]: why do you check `resBody.Code != http.StatusOK twice` ?
