### PR TITLE
fix: config-ui: refactor connection manager save workflow + enhancements

### LINKED ISSUE #2923: [Bug][Config-UI] Data Integrations - Toast Notifications odd behavior on Add Connections
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Unable to add a New Connection** for any provider. Users are redirected to the Manage Connections Screen without the connection successfully saving.

### What you expected to happen

A New Connection is Added successfully. User receives a successful Toast warning Stating as such.

### How to reproduce

Try adding a NEW Connection for Any Provider.

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by e2corporation**
### 📦  Config-UI / Data Integrations / Connection Manager

- [x] `Fix` Connection Save Handling and remove extra `savePromise` added during recent refactor
- [x] `Fix` Memoize the `connectionSavePayload` and remove `Switched` payloads
- [x] `Fix` Restore `Success` Toast Notifications on Connection Save
- [x] `Fix` Restore `Error` Toast Notifications on Connection Save API Failure
- [x] `Fix` Remove `setTimeout` Handler post-save
- [x] `Fix` Remove legacy inlined connection test post-save
- [x] `Feat` Add **Connection** _Data Model_ (`models/Connection.js`)
- [x] `Feat` Add **Data Scope Connection** _Data Model_ (`models/DataScopeConnection.js`)
- [x] `Feat` Add **Provider List Connection** _Data Model_ (`models/ProviderListConnection.js`)
- [x] `Feat` Add **Transformation Settings** _Data Model_ (`models/TransformationSettings.js`)
- [x] `Feat` Add **JIRA Board** _Data Model_ (`models/JiraBoard.js`)
- [x] `Feat` Add **Gitlab Project** _Data Model_ (`models/GitlabProject.js`)
- [x] `Feat` Add **Github Project** _Data Model_ (`models/GithubProject.js`)
- [x] `Feat` Add Full Title Tooltip to Gitlab Projects Selector (_Tag_ Item)
- [x] `Refactor` Change legacy uppercase Connection `ID` prop to `id`
- [x] `Refactor` change Connection Prop `rateLimit` to `rateLimitPerHour` for future consistency
- [x] `Refactor` Lift `Normal` and `Advanced` Connection Builders to DSM Hook
- [x] `Fix` #2944 
- [x] `Fix` Resolve Lint warnings with missing React Effect Dependencies
- [x] `Test` Data Integrations

### Description

This PR performs refactoring enhancements to **Connection Manager Hook** that restores the desired Save Handling workflow for data connections. After a connection is successfully saved, the user is redirected back to the Manage Connections screen _only_ when Adding a New Connection. When Modifying an existing Connection, the user will remain on the Configure Connection screen after saving.

### Does this close any open issues?
Closes #2923

### Screenshots
Screen Shot 2022-09-04 at 9 00 50 AM
Screen Shot 2022-09-04 at 12 35 42 AM
Screen Shot 2022-09-04 at 12 15 28 AM
Screen Shot 2022-09-04 at 12 16 05 AM
Screen Shot 2022-09-04 at 12 19 26 AM

### CODE REVIEW

File: config-ui/src/components/actions/DeleteAction.jsx [hunk 1]
```diff
@@ -28,21 +28,25 @@ import {
...
     <Popover
-      key={`delete-popover-key-${connection.ID}`}
+      key={`delete-popover-key-${connection.id}`}
       className='trigger-delete-connection'
       popoverClassName='popover-delete-connection'
       position={Position.RIGHT}
       autoFocus={false}
       enforceFocus={false}
-      isOpen={id === connection.ID}
+      isOpen={id !== null && id === connection.id}
```
Comment (mintsweet) [inline config-ui/src/components/actions/DeleteAction.jsx:49]: `id && id === connection.id`?

File: config-ui/src/hooks/useConnectionManager.jsx [hunk 2]
```diff
@@ -42,15 +43,13 @@ function useConnectionManager (
...
   const [proxy, setProxy] = useState()
-  const [rateLimit, setRateLimit] = useState(0)
+  const [rateLimitPerHour, setRateLimitPerHour] = useState(0)
   const [token, setToken] = useState()
-  const [initialTokenStore, setInitialTokenStore] = useState({
-    0: '',
-    1: '',
-    2: ''
-  })
+  const defaultTokenStore = useMemo(() => ({ 0: '', 1: '', 2: '' }), [])
```
Comment (mintsweet) [inline config-ui/src/hooks/useConnectionManager.jsx:51]: meaningless useMemo

File: config-ui/src/hooks/useConnectionManager.jsx [hunk 3]
```diff
@@ -42,15 +43,13 @@ function useConnectionManager (
...
+  const [initialTokenStore, setInitialTokenStore] = useState(defaultTokenStore)
```
Comment (mintsweet) [inline config-ui/src/hooks/useConnectionManager.jsx:52]: why `useState(['', '', ''])`?

File: config-ui/src/hooks/useConnectionManager.jsx [hunk 4]
```diff
@@ -141,70 +154,66 @@ function useConnectionManager (
...
-        break
-      case Providers.GITLAB:
-        connectionPayload = {
-          name: name,
-          endpoint: endpointUrl,
-          token: token,
-          proxy: proxy,
-          rateLimitPerHour: rateLimit,
-          ...connectionPayload,
+  const notifyConnectionSaveSuccess = useCallback((message = 'Connection saved successfully.') => {
```
Comment (mintsweet) [inline config-ui/src/hooks/useConnectionManager.jsx:157]: meaningless useCallback

File: config-ui/src/hooks/useConnectionManager.jsx [hunk 5]
```diff
@@ -141,70 +154,66 @@ function useConnectionManager (
...
+        const fetch = async () => {
+          const f = await request.get(
+            `${DEVLAKE_ENDPOINT}/plugins/${provider?.id}/connections/${cId || connectionId}`
+          )
+          const connectionData = f.data
+          console.log('>> RAW CONNECTION DATA FROM API...', connectionData)
+          setActiveConnection(new Connection({
+            ...connectionData
+          }))
+          setTimeout(() => {
```
Comment (mintsweet) [inline config-ui/src/hooks/useConnectionManager.jsx:189]: why `try {} catch {} finall { setIsFetching(false) }`?

File: config-ui/src/hooks/useConnectionManager.jsx [hunk 6]
```diff
@@ -141,70 +154,66 @@ function useConnectionManager (
...
+            setIsFetching(false)
+          }, 500)
         }
-        break
-    }
+        fetch()
```
Comment (mintsweet) [inline config-ui/src/hooks/useConnectionManager.jsx:193]: `await`?

File: config-ui/src/hooks/useConnectionManager.jsx [hunk 7]
```diff
@@ -225,9 +234,15 @@ function useConnectionManager (
           connection: { ...s.data },
           errors: s.isAxiosError ? [s.message] : [],
         }
+        setIsSaving(false)
+        setSaveComplete(saveResponse.success ? new Connection(s.data) : false)
+        if (!saveResponse.success) { notifyConnectionSaveFailure(s.data || s.message) }
```
Comment (mintsweet) [inline config-ui/src/hooks/useConnectionManager.jsx:239]: throw a custom error?

File: config-ui/src/hooks/useConnectionManager.jsx [hunk 8]
```diff
@@ -546,69 +493,45 @@ function useConnectionManager (
...
-      ToastNotification.clear()
-      // ToastNotification.show({ message: `Fetched settings for ${activeConnection.name}.`, intent: 'success', icon: 'small-tick' })
+      setName(activeConnection?.name)
+      setEndpointUrl(activeConnection?.endpoint)
+      setRateLimitPerHour(activeConnection?.rateLimitPerHour)
+      setProxy(activeConnection?.proxy)
+      setUsername(activeConnection?.username)
+      setPassword(activeConnection?.password)
+      setToken(activeConnection?.token)
+      setInitialTokenStore(activeConnection?.token
```
Comment (mintsweet) [inline config-ui/src/hooks/useConnectionManager.jsx:510]: terrible variable definition, why not in an object?

File: config-ui/src/hooks/useConnectionManager.jsx (hunk 4 above)
Comment (e2corporation) [reply config-ui/src/hooks/useConnectionManager.jsx:157]: Have you given thought or used callbacks before at all prior to making comments? This is reusable notification success helper. No it's not meaningless, any funcs that are internal to the class are to be wrapped in callbacks to prevent unwanted re-renders.

File: config-ui/src/hooks/useConnectionManager.jsx (hunk 8 above)
Comment (e2corporation) [reply config-ui/src/hooks/useConnectionManager.jsx:510]: These are controlled properties for a detailed connection form, if you don't understand something it doesn't make it terrible.

File: config-ui/src/hooks/useConnectionManager.jsx (hunk 3 above)
Comment (e2corporation) [reply config-ui/src/hooks/useConnectionManager.jsx:52]: Because the default tokenStore is reused in several places why would I want to re-create a generic object each time when I can create a default token store instead? Please read the code before making baseless comments.

File: config-ui/src/hooks/useConnectionManager.jsx (hunk 6 above)
Comment (e2corporation) [reply config-ui/src/hooks/useConnectionManager.jsx:193]: This `fetch` here is an internal helper method not the HTTP Fetch API.

File: config-ui/src/hooks/useConnectionManager.jsx (hunk 2 above)
Comment (e2corporation) [reply config-ui/src/hooks/useConnectionManager.jsx:51]: Meaningless feedback. It's a memo with no compute dependencies at the moment, so the const can be defined in the component.

File: config-ui/src/hooks/useConnectionManager.jsx (hunk 7 above)
Comment (e2corporation) [reply config-ui/src/hooks/useConnectionManager.jsx:239]: Not needed here, notifications are being dispatched on-demand.

File: config-ui/src/hooks/useConnectionManager.jsx (hunk 5 above)
Comment (e2corporation) [reply config-ui/src/hooks/useConnectionManager.jsx:189]: This isn't a problem, the `Finally` catch block could be implemented, for now controlling fetch state is handled directly within try/catch.

File: config-ui/src/hooks/useConnectionManager.jsx (hunk 4 above)
Comment (mintsweet) [reply config-ui/src/hooks/useConnectionManager.jsx:157]: overuse affects more than re-rendering, I don't see any dependencies preventing re-rendering.

Comment (mintsweet) [reply config-ui/src/hooks/useConnectionManager.jsx:157]: https://www.developerway.com/posts/how-to-use-memo-use-callback 
This article roughly explains

File: config-ui/src/hooks/useConnectionManager.jsx (hunk 2 above)
Comment (mintsweet) [reply config-ui/src/hooks/useConnectionManager.jsx:51]: I think the defaultTokenStore should be placed outside the component so that it will only be declared when the app is initialized.useMemo brings performance issues.

File: config-ui/src/hooks/useConnectionManager.jsx (hunk 3 above)
Comment (mintsweet) [reply config-ui/src/hooks/useConnectionManager.jsx:52]: Well, I didn't look closely.

File: config-ui/src/hooks/useConnectionManager.jsx (hunk 5 above)
Comment (mintsweet) [reply config-ui/src/hooks/useConnectionManager.jsx:189]: I am talking about the problem of setTimeout. If the response time is greater than the set time, the pop-up prompt is wrong.

File: config-ui/src/hooks/useConnectionManager.jsx (hunk 7 above)
Comment (mintsweet) [reply config-ui/src/hooks/useConnectionManager.jsx:239]: I see that there are duplicate notifyConnectionSaveFailure functions, my task is unnecessary.
At the same time error handling is unified.

File: config-ui/src/hooks/useConnectionManager.jsx (hunk 8 above)
Comment (mintsweet) [reply config-ui/src/hooks/useConnectionManager.jsx:510]: Good code is easy to understand.

Comment (e2corporation) [reply config-ui/src/hooks/useConnectionManager.jsx:510]: @mintsweet I wonder if you'd be the best judge to decide what dictates "good code"

**Comment by e2corporation** [comment]
@mintsweet Your tone comes across like that of a disgruntled community developer member blurting out random comments as you struggle try to find something wrong to post about. None of the issues you mention cause any usability bugs or have much to do with the intent of this PR. Please avoid polluting my pull request with senseless feedback.

**Comment by mintsweet** [comment]
@e2corporation sorry, my English is not very good, and my expression may be too abrupt.
It's my fault to make you feel uncomfortable. I sincerely hope devlake becomes better.

File: config-ui/src/models/GithubProject.js [hunk 9]
```diff
@@ -0,0 +1,61 @@
...
+ * @property {string|number?} value
+ * @property {string|number?} name
+ * @property {string|number?} title
+ * @property {string?} owner
+ * @property {string?} repo
+ * @property {boolean?} useApi
+ * @property {project|board?} variant
+ */
+class GitHubProject {
+  constructor (data = {}) {
```
Comment (mintsweet) [inline config-ui/src/models/GithubProject.js:32]:
```js
data = {
  id: null,
  key: null,
  ...
}

this.id = data.id;
```

do you think it would be better？

Comment (e2corporation) [reply config-ui/src/models/GithubProject.js:32]: this default `data` object will get get replaced when the model is constructed, so these preserved keys initialized as null within this data obj be wiped. The current behavior of `this.id = data?.id || null` should be sufficient for now.

**Comment by e2corporation** [comment]
> @e2corporation sorry, my English is not very good, and my expression may be too abrupt. It's my fault to make you feel uncomfortable. I sincerely hope devlake becomes better.

@mintsweet Thanks for taking the time to clarify, I couldn't tell I thought you were just being direct. Had you introduced yourself as one of our new colleagues I would have been more receptive to your feedback and found it less invasive, though code review is not the really the ideal place to start as you are just getting adjusted to the codebase. There will be opportunities going forward for you to apply some of your suggestions and ideas such as implementing the `Finally` block on try/catch statements that could benefit from them etc. I will make our collaboration a smoother process for you going forward.

For now, focusing your efforts on Feature development tickets for DORA would be ideal for this milestone.

**Review by klesh — APPROVED** [review]
LGTM
