### PR TITLE
fix: jenkins transformation rules have not in effect and getjobs api error

### LINKED ISSUE #4057: [Bug][jenkins] jenkins transformation rules have not in effect.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. jenkins transformation rules have not in effect in `cicd_task` table `type` column.

2. jenkins get job api name in the path is missing. 
image

### What do you expect to happen

jenkins transformation rules have in effect in `cicd_task` table `type` column.

### How to reproduce

run the jenkins plugin.

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by abeizn**
### Summary
1. jenkins v200 add transformation rule id for prepareTaskData usage.
2. fix getjobs api error

### Does this close any open issues?
Closes #4057 

### Screenshots

image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: plugins/jenkins/api/blueprint_v200.go [hunk 1]
```diff
@@ -58,10 +58,19 @@ func makeDataSourcePipelinePlanV200(
...
+		err := basicRes.GetDal().First(jenkinsJob, dal.Where(`connection_id = ? AND full_name = ?`, connectionId, bpScope.Id))
+		if err != nil {
+			return nil, errors.Default.Wrap(err, fmt.Sprintf("fail to find transformation_rule_id by %s", bpScope.Id))
+		}
+
+		// construct task options for Jenkins
 		options := make(map[string]interface{})
 		options["scopeId"] = bpScope.Id
 		options["connectionId"] = connectionId
+		options["TransformationRuleId"] = jenkinsJob.TransformationRuleId
```
Comment (warren830) [inline plugins/jenkins/api/blueprint_v200.go:72]: why uppercase for the first alphabet of TransformationRuleId?

**Review by warren830 — CHANGES_REQUESTED** [review]
please check the comments

**Review by warren830 — APPROVED** [review]
LGTM
