### PR TITLE
fix: add db close connection

### LINKED ISSUE #4711: [Bug][starrocks] the starrocks db connections are not released
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

there are many pg connections that are idle after this query. I suspect that the starrocks db connections are not released.

### What do you expect to happen

gorm close

### How to reproduce

use starrocks plugin

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by abeizn**
### Summary
add gorm close.

When using GORM to connect to the database, if you do not manually call the db.Close() method to close the connection, the connection will be returned to the GORM connection pool after the program is executed. At this point, the state of the connection will change to "idle", indicating that the connection is idle and available for other requests.

In GORM, if there is no connection available in the connection pool, then GORM will create a new connection. If there is a free connection in the connection pool, GORM will get a connection from the connection pool and assign it to the request.

Under normal circumstances, there should always be some idle connections in the connection pool, so as to meet the needs of concurrent requests. If the number of idle connections in the connection pool is low, it may cause requests to wait for a long time to obtain a connection, thereby affecting the performance of the application.

Therefore, although it is not necessary to explicitly call the db.Close() method to close the connection when using GORM to connect to the database, it is recommended to call this method explicitly before the program exits to ensure that the connection in the connection pool is released and avoid "idle" Too many connections cause the connection pool to fail, thereby affecting the performance of the application.

### Does this close any open issues?
Closes #4711 

### Screenshots
img_v2_93e99a5e-a708-4c92-8bfb-8cef800b346g

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/plugins/starrocks/tasks/tasks.go [hunk 1]
```diff
@@ -414,6 +419,11 @@ func getDbInstance(c plugin.SubTaskContext) (db dal.Dal, err error) {
 			return nil, errors.NotFound.New(fmt.Sprintf("unsupported source type %s", config.SourceType))
 		}
 		db = dalgorm.NewDalgorm(o)
+		sqlDB, err := o.DB()
+		if err != nil {
+			return nil, err
+		}
+		defer sqlDB.Close()
```
Comment (mindlesscloud) [inline backend/plugins/starrocks/tasks/tasks.go:426]: the connection will be closed when the function `getDbInstance` returns

**Review by mindlesscloud — COMMENTED** [review]
LGTM

**Review by mindlesscloud — APPROVED** [review]
