### PR TITLE
fix: add param datasource for dora enrichTasksEnv

### LINKED ISSUE #2876: [Feature][dora] enrichPipelineEnv for Deployment Frequency
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

enrichPipelineEnv for Deployment Frequency accepts argument environmentRegex and enrich cicd_pipelines.environment against cicd_pipelines.name, along with scope parameter

### Use case

_No response_

### Related issues

#2853

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by abeizn**
# Summary

add param datasource for dora enrichTasksEnv

### Does this close any open issues?
Closes #2876 

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: plugins/dora/tasks/cicd_task_env_enricher.go [hunk 1]
```diff
@@ -18,6 +18,7 @@ limitations under the License.
 package tasks
 
 import (
+	"database/sql"
```
Comment (warren830) [inline plugins/dora/tasks/cicd_task_env_enricher.go:21]: Why do we import this pkg?

Comment (abeizn) [reply plugins/dora/tasks/cicd_task_env_enricher.go:21]: 62: var cursor *sql.Rows

**Review by warren830 — APPROVED** [review]
LGTM
