### PR TITLE
fix(jira): optimize collector for remotelink worklog changelog

### LINKED ISSUE #4239: [Bug][Jira] Inefficient collection for changelog/remotelink/worklog
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Compared to v0.14, we now spent more time collecting Jira (a board previously taking 40 mins now takes 2 hours).

### What do you expect to happen

It should spend a similar time to collect Jira compared to 0.14

### How to reproduce

Collect Jira by 0.14 and 0.15
then compare the time consumed 

### Anything else

The fix of this issue needs to be cherry-picked back to the release-v0.15 branch.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by warren830**
### Summary
Modify incremental collection to make collector work efficient.

### Does this close any open issues?
Closes #4239 

### Screenshots
image
### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/plugins/jira/tasks/issue_changelog_collector.go [hunk 1]
```diff
@@ -74,7 +74,9 @@ func CollectIssueChangelogs(taskCtx plugin.SubTaskContext) errors.Error {
 		dal.Groupby("i.issue_id, i.updated"),
 	}
 	incremental := collectorWithState.IsIncremental()
-	if incremental {
+	if incremental && collectorWithState.LatestState.LatestSuccessStart != nil {
```
Comment (likyh) [inline backend/plugins/jira/tasks/issue_changelog_collector.go:77]: `collectorWithState.LatestState.LatestSuccessStart != nil` is not necessary. because incremental contains it.

File: backend/plugins/jira/tasks/worklog_collector.go [hunk 2]
```diff
@@ -66,7 +66,9 @@ func CollectWorklogs(taskCtx plugin.SubTaskContext) errors.Error {
 		dal.Groupby("i.issue_id, i.updated"),
 	}
 	incremental := collectorWithState.IsIncremental()
-	if incremental {
+	if incremental && collectorWithState.LatestState.LatestSuccessStart != nil {
+		clauses = append(clauses, dal.Having("i.updated > ? AND (i.updated > max(wl.issue_updated) OR max(wl.issue_updated) IS NULL)", collectorWithState.LatestState.LatestSuccessStart))
```
Comment (likyh) [inline backend/plugins/jira/tasks/worklog_collector.go:70]: It looks like ` AND COUNT(wl.worklog_id) > 0` is necessary because maybe issue updated but worklog is empty either.

File: backend/plugins/jira/tasks/issue_changelog_collector.go (hunk 1 above)
Comment (warren830) [reply backend/plugins/jira/tasks/issue_changelog_collector.go:77]: I saw the old code you wrote is :

File: backend/plugins/jira/tasks/worklog_collector.go [hunk 3]
```diff
@@ -66,7 +66,9 @@ func CollectWorklogs(taskCtx plugin.SubTaskContext) errors.Error {
...
+	} else {
 		clauses = append(clauses, dal.Having("i.updated > max(wl.issue_updated) OR  (max(wl.issue_updated) IS NULL AND COUNT(wl.worklog_id) > 0)"))
```
[the remark this answers is not in the document]
Comment (warren830) [reply backend/plugins/jira/tasks/worklog_collector.go:72]: This is old logic from v0.14, as we don't have enough time to test, so I kept that

File: backend/plugins/jira/tasks/issue_changelog_collector.go (hunk 1 above)
Comment (likyh) [reply backend/plugins/jira/tasks/issue_changelog_collector.go:77]: Emm, it's not right 😂

File: backend/plugins/jira/tasks/worklog_collector.go (hunk 2 above)
Comment (warren830) [reply backend/plugins/jira/tasks/worklog_collector.go:70]: Seems right

File: backend/plugins/jira/tasks/issue_changelog_collector.go (hunk 1 above)
Comment (warren830) [reply backend/plugins/jira/tasks/issue_changelog_collector.go:77]: > Emm, it's not right 😂

OK, I will fix it...

File: backend/plugins/jira/tasks/issue_changelog_collector.go [hunk 4]
```diff
@@ -75,7 +75,17 @@ func CollectIssueChangelogs(taskCtx plugin.SubTaskContext) errors.Error {
 	}
 	incremental := collectorWithState.IsIncremental()
 	if incremental {
-		clauses = append(clauses, dal.Having("i.updated > max(c.issue_updated) OR  (max(c.issue_updated) IS NULL AND COUNT(c.changelog_id) > 0)"))
+		clauses = append(clauses, dal.Having("i.updated > ? AND (i.updated > max(c.issue_updated) OR (max(c.issue_updated) IS NULL AND COUNT(c.changelog_id) > 0))", collectorWithState.LatestState.LatestSuccessStart))
+	} else {
+		/*
+			i.updated > max(rl.issue_updated) was deleted because for non-incremental collection,
+			max(rl.issue_updated) will only be one of null, less or equal to i.updated
+			so i.updated > max(rl.issue_updated) is always false.
```
Comment (likyh) [inline backend/plugins/jira/tasks/issue_changelog_collector.go:83]: Hmmm. `i.updated` will  `> max(rl.issue_updated)` when the issue updated and is collected by IssueCollector.

Comment (likyh) [reply backend/plugins/jira/tasks/issue_changelog_collector.go:83]: You mean `i.updated > max(rl.issue_updated) is always false` when `!incremental`. ok, that's right.

**Review by likyh — APPROVED** [review]
